// *** CIVILIAN ***

civilians = [
	"C_man_1",
	"C_man_p_beggar_F",
	"C_man_1_2_F",
	"C_man_p_fugitive_F",
	"C_man_hunter_1_F",
	"C_Man_Fisherman_01_F",
	"C_man_sport_1_F",
	"C_man_sport_3_F",
	"C_man_sport_2_F",
	"C_Man_Messenger_01_F",
	"C_Story_Mechanic_01_F",
	"C_Man_casual_4_v2_F",
	"C_Man_casual_5_v2_F",
	"C_Man_casual_6_v2_F",
	"C_Man_casual_7_F",
	"C_Man_casual_8_F",
	"C_Man_casual_9_F",
	"C_Man_smart_casual_1_F",
	"C_Man_ConstructionWorker_01_Blue_F",
	"C_Man_ConstructionWorker_01_Black_F",
	"C_journalist_F",
	"C_man_shorts_2_F",
	"C_man_w_worker_F",
	"C_Paramedic_01_base_F",
	"C_Man_UAV_06_F",
	"C_Man_UtilityWorker_01_F"
];

civilian_vehicles = [
	"OPTRE_M274_ATV",
	"OPTRE_UNSC_falcon_PD",
	"OPTRE_Genet",
	"OPTRE_M12_CIV",
	"OPTRE_M12_CIV2",
	"OPTRE_M12_FAV_PD",
	"C_Offroad_01_comms_F",
	"OPTRE_cart",
	"OPTRE_forklift",
	"SUV_01_base_black_F",
	"OPTRE_M274_ATV",
	"OPTRE_UNSC_falcon_PD",
	"OPTRE_Genet",
	"OPTRE_M12_CIV",
	"OPTRE_M12_CIV2",
	"OPTRE_M12_FAV_PD",
	"OPTRE_M274_ATV",
	"C_Offroad_01_comms_F",
	"OPTRE_cart",
	"OPTRE_forklift",
	"SUV_01_base_black_F"
];