//Blacklist Items

whitelisted_from_arsenal = [
	"MineDetector",
	"Binocular",
	"Rangefinder",
	"ItemCompass",
	"ItemGPS",
	"ItemMap",
	"ItemRadio",
	"ItemWatch",
	"HandGrenade",
	"MiniGrenade",
	"I_IR_Grenade",
	"Laserbatteries",
	"APERSMine_Range_Mag",
	"APERSTripMine_Wire_Mag",
	"APERSBoundingMine_Range_Mag",
	"ATMine_Range_Mag",
	"SatchelCharge_Remote_Mag",
	"DemoCharge_Remote_Mag",
	"SLAMDirectionalMine_Wire_Mag",
	"ClaymoreDirectionalMine_Remote_Mag",

	// some AAF weapons
	"arifle_AKM_F",
	"arifle_AK12_F",
	"arifle_TRG20_F",
	"arifle_TRG20_ACO_F",
	"arifle_Mk20_ACO_F",
	"arifle_Mk20_F",
	"arifle_Mk20_GL_ACO_F",
	"arifle_MSBS65_black_aco_F",
	"arifle_MSBS65_Mark_SOS_LP_BI_F",

	// some AAF gears
	"H_Bandanna_khk",
	"H_Beret_blk",
	"H_Booniehat_khk",
	"H_HelmetHBK_F",
	"H_HelmetIA_camo",
	"U_BG_Guerilla1_1",
	"U_C_HunterBody_grn",
	"U_I_C_Soldier_Camo_F",
	"U_I_C_Soldier_Para_1_F",
	"U_I_C_Soldier_Para_1_F",
	"U_I_C_Soldier_Para_4_F",
	"U_I_C_Soldier_Para_5_F",
	"U_I_CBRN_Suit_01_AAF_F",
	"U_I_CombatUniform",
	"U_I_CombatUniform_shortsleeve",
	"V_I_G_resistanceLeader_F",
	"V_PlateCarrierIA2_dgtl",
	"V_PlateCarrierIAGL_dgtl"
];
