//Blacklist Items
blacklisted_bag = [
	"R3F_Sac_FNMAG58_weapon",
    "R3F_MMP_STATIC_Bag_support",
	"R3F_Sac_FNMAG58_support",
    "R3F_MMP_STATIC_Bag",
	"R3F_Support_MO81_LLR",
	"R3F_Tube_MO81_LLR",
	"R3F_DLO_backpack"
];

blacklisted_weapon = [
	"arifle_Katiba_GL_Nstalker_pointer_F",
	"srifle_DMR_04_NS_LP_F",
	"optic_Nightstalker",
	"optic_tws",
	"optic_tws_mg",
	"H_HelmetO_ViperSP_hex_F",
	"H_HelmetO_ViperSP_ghex_F",
	"U_O_V_Soldier_Viper_hex_F",
	"U_O_V_Soldier_Viper_F",
	"O_V_Soldier_Viper_F",
	"O_V_Soldier_Viper_hex_F",
	"Pylon",
	"Vorona",
	"_missiles",
	"_Leaflets",
	"_esd_",
	"R3F_LGI_DEM",
	"R3F_securite_mag",
	"R3F_securite_fn_mag"
];

whitelisted_from_arsenal = [
	"FirstAidKit",
	"Medikit",
	"ToolKit",
	"MineDetector",
	"Binocular",
	"Rangefinder",
	"NVGoggles",
	"NVGoggles_OPFOR",
	"NVGoggles_INDEP",
	"NVGogglesB_blk_F",
	"NVGogglesB_grn_F",
	"NVGogglesB_gry_F",
	"ItemCompass",
	"ItemGPS",
	"ItemMap",
	"ItemRadio",
	"ItemWatch",
	"Bandage",
	"HandGrenade",
	"MiniGrenade",
	"Laserbatteries",
	"B_UavTerminal",
	"U_B_Wetsuit",
    "V_RebreatherB",
    "G_B_Diving",	
	"APERSMine_Range_Mag",
	"APERSBoundingMine_Range_Mag",
	"ATMine_Range_Mag",
	"SatchelCharge_Remote_Mag",
	"SLAMDirectionalMine_Wire_Mag"
];
