/**
 * Constantes pour rendre les d�finitions des bo�tes de dialogue plus lisible et maintenable
 */

#define R3F_LOG_ID_TRANSPORTEUR_START 65430
#define R3F_LOG_IDD_DLG_CONTENU_VEHICULE (R3F_LOG_ID_TRANSPORTEUR_START + 1)
#define R3F_LOG_IDC_DLG_CV_CAPACITE_VEHICULE (R3F_LOG_ID_TRANSPORTEUR_START + 2)
#define R3F_LOG_IDC_DLG_CV_LISTE_CONTENU (R3F_LOG_ID_TRANSPORTEUR_START + 3)
#define R3F_LOG_IDC_DLG_CV_BTN_DECHARGER (R3F_LOG_ID_TRANSPORTEUR_START + 4)
#define R3F_LOG_IDC_DLG_CV_TITRE (R3F_LOG_ID_TRANSPORTEUR_START + 10)
#define R3F_LOG_IDC_DLG_CV_CREDITS (R3F_LOG_ID_TRANSPORTEUR_START + 11)
#define R3F_LOG_IDC_DLG_CV_BTN_FERMER (R3F_LOG_ID_TRANSPORTEUR_START + 12)
#define R3F_LOG_IDC_DLG_CV_JAUGE_CHARGEMENT (R3F_LOG_ID_TRANSPORTEUR_START + 13)
