// Mod signature
GRLIB_MOD_signature = [];						// Used to filter several MOD items

// Default Personal Arsenal
private _path = format ["mod_template\%1\arsenal.sqf", GRLIB_mod_west];
[_path] call F_getTemplateFile;
private _ret = [] call compileFinal preprocessFileLineNumbers "addons\LARs\default_personal_arsenal.sqf";
if (isNil "default_personal_arsenal") then { default_personal_arsenal = _ret };

// Default LRX blacklist
GRLIB_blacklisted_bag = [
	"B_Static_Designator_01_weapon_F",
	"B_W_Static_Designator_01_weapon_F",
	"O_Static_Designator_02_weapon_F",
	"B_UAV_06_backpack_F",
	"O_UAV_06_backpack_F",
	"I_UAV_06_backpack_F",
	"B_UAV_06_medical_backpack_F",
	"O_UAV_06_medical_backpack_F",
	"I_UAV_06_medical_backpack_F",
	"B_UGV_02_Science_backpack_F",
	"O_UGV_02_Science_backpack_F",
	"I_UGV_02_Science_backpack_F",
	"B_UGV_02_Demining_backpack_F",
	"O_UGV_02_Demining_backpack_F",
	"I_UGV_02_Demining_backpack_F",
	"B_Respawn_Sleeping_bag_blue_F",
	"B_Respawn_Sleeping_bag_brown_F",
	"B_Respawn_TentDome_F",
	"B_Respawn_Sleeping_bag_F",
	"B_Respawn_TentA_F",
	"B_Patrol_Respawn_bag_F",
	"B_Patrol_Respawn_tent_F",
	"B_HMG_01_support_F",
	"O_HMG_01_support_F",
	"I_HMG_01_support_F",
	"B_HMG_01_support_high_F",
	"O_HMG_01_support_high_F",
	"I_HMG_01_support_high_F",
	"I_HMG_01_A_weapon_F",
	"B_HMG_01_A_weapon_F",
	"O_HMG_01_A_weapon_F",
	"O_HMG_01_weapon_F",
	"B_HMG_01_weapon_F",
	"I_HMG_01_weapon_F",
	"I_HMG_01_high_weapon_F",
	"O_HMG_01_high_weapon_F",
	"B_HMG_01_high_weapon_F",
	"B_HMG_01_support_grn_F",
	"B_HMG_01_Weapon_grn_F",
	"B_HMG_02_high_weapon_F",
	"B_G_HMG_02_high_weapon_F",
	"I_HMG_02_high_weapon_F",
	"O_HMG_02_high_weapon_F",
	"B_HMG_02_support_F",
	"B_G_HMG_02_support_F",
	"I_HMG_02_support_F",
	"O_HMG_02_support_F",
	"B_HMG_02_support_high_F",
	"B_G_HMG_02_support_high_F",
	"I_HMG_02_support_high_F",
	"O_HMG_02_support_high_F",
	"B_HMG_02_weapon_F",
	"B_G_HMG_02_weapon_F",
	"I_HMG_02_weapon_F",
	"O_HMG_02_weapon_F",
	"I_GMG_01_A_weapon_F",
	"O_GMG_01_A_weapon_F",
	"B_GMG_01_A_weapon_F",
	"O_GMG_01_weapon_F",
	"I_GMG_01_weapon_F",
	"B_GMG_01_weapon_F",
	"B_GMG_01_high_weapon_F",
	"I_GMG_01_high_weapon_F",
	"O_GMG_01_high_weapon_F",
	"I_Mortar_01_support_F",
	"B_Mortar_01_support_F",
	"O_Mortar_01_support_F",
	"B_Mortar_01_weapon_F",
	"O_Mortar_01_weapon_F",
	"I_Mortar_01_weapon_F",
	"I_E_HMG_02_support_F",
	"I_C_HMG_02_support_F",
	"I_G_HMG_02_support_F",
	"O_G_HMG_02_support_F",
	"I_E_HMG_02_support_high_F",
	"I_C_HMG_02_support_high_F",
	"I_G_HMG_02_support_high_F",
	"O_G_HMG_02_support_high_F",
	"I_E_HMG_02_weapon_F",
	"I_C_HMG_02_weapon_F",
	"I_G_HMG_02_weapon_F",
	"O_G_HMG_02_weapon_F",
	"I_E_HMG_02_high_weapon_F",
	"I_C_HMG_02_high_weapon_F",
	"I_G_HMG_02_high_weapon_F",
	"O_G_HMG_02_high_weapon_F",
	"UGV_02_backpack_base_F",
	"UGV_02_Science_backpack_base_F",
	"UGV_02_Demining_backpack_base_F",
	"I_E_UGV_02_Science_backpack_F",
	"I_E_UGV_02_Demining_backpack_F",
	"C_IDAP_UGV_02_Demining_backpack_F",
	"I_E_UAV_01_backpack_F",
	"I_E_UAV_06_backpack_F",
	"I_E_UAV_06_medical_backpack_F",
	"I_E_HMG_01_support_F",
	"I_E_HMG_01_support_high_F",
	"I_E_Mortar_01_support_F",
	"I_E_GMG_01_Weapon_F",
	"I_E_GMG_01_A_Weapon_F",
	"I_E_GMG_01_high_Weapon_F",
	"I_E_HMG_01_Weapon_F",
	"I_E_HMG_01_high_Weapon_F",
	"I_E_HMG_01_A_Weapon_F",
	"I_E_Mortar_01_Weapon_F",
	"I_E_AT_01_weapon_F",
	"I_E_AA_01_weapon_F",
	"B_AA_01_weapon_F",
	"O_AA_01_weapon_F",
	"I_AA_01_weapon_F",
	"B_AT_01_weapon_F",
	"O_AT_01_weapon_F",
	"I_AT_01_weapon_F",
	"I_UAV_01_backpack_F",
	"B_UAV_01_backpack_F",
	"O_UAV_01_backpack_F",
	"C_IDAP_UAV_01_backpack_F",
	"UAV_06_backpack_base_F",
	"UAV_06_medical_backpack_base_F",
	"C_IDAP_UAV_06_backpack_F",
	"C_UAV_06_backpack_F",
	"C_IDAP_UAV_06_antimine_backpack_F",
	"C_IDAP_UAV_06_medical_backpack_F",
	"C_UAV_06_medical_backpack_F",
	"B_Mortar_01_support_grn_F",
	"B_GMG_01_Weapon_grn_F",
	"B_Mortar_01_Weapon_grn_F"
];

GRLIB_blacklisted_from_arsenal = [
	"Pylon",
	"_Leaflets",
	"_missiles",
	"_used",
	"_esd_",
	"Zasleh2",
	"CMFlare",
	"SmokeLauncher",
	"FlareLauncher",
	"weapon_Fighter",
	"arifle_Katiba_GL_Nstalker_pointer_F",
	"srifle_DMR_04_NS_LP_F",
	"optic_Nightstalker",
	"optic_tws",
	"optic_tws_mg",
	"B_Protagonist_VR_F",
	"U_B_Protagonist_VR",
	"O_Protagonist_VR_F",
	"U_O_Protagonist_VR",
	"I_Protagonist_VR_F",
	"U_I_Protagonist_VR",
	"C_Protagonist_VR_F",
	"U_C_Protagonist_VR",
	"H_HelmetO_ViperSP_hex_F",
	"H_HelmetO_ViperSP_ghex_F",
	"U_O_V_Soldier_Viper_hex_F",
	"U_O_V_Soldier_Viper_F",
	"O_V_Soldier_Viper_F",
	"O_V_Soldier_Viper_hex_F"
] + GRLIB_blacklisted_bag + blacklisted_bag + blacklisted_weapon;

// Default LRX whitelist
GRLIB_whitelisted_from_arsenal = [
	mobile_respawn_bag,
	PAR_Medikit,
	PAR_AidKit,
	"ToolKit",
	"B_Parachute",
	"arifle_SDAR_F",
	"20Rnd_556x45_UW_mag",
	"U_B_Wetsuit",
	"U_O_Wetsuit",
	"U_I_Wetsuit",
	"V_RebreatherB",
	"V_RebreatherIA",
	"V_RebreatherIR",
	"SatchelCharge_Remote_Mag",
	"DemoCharge_Remote_Mag",
	"HandGrenade",
	"MiniGrenade",
	// Flares
	"FlareWhite_F",
	"FlareGreen_F",
	"FlareRed_F",
	"FlareYellow_F",
	"UGL_FlareWhite_F",
	"3Rnd_UGL_FlareWhite_F",
	"UGL_FlareGreen_F",
	"3Rnd_UGL_FlareGreen_F",
	"UGL_FlareRed_F",
	"3Rnd_UGL_FlareRed_F",
	"UGL_FlareYellow_F",
	"3Rnd_UGL_FlareYellow_F",
	"UGL_FlareCIR_F",
	"3Rnd_UGL_FlareCIR_F",
	// Grenade shell
	"1Rnd_HE_Grenade_shell",
	"3Rnd_HE_Grenade_shell",
	"1Rnd_Smoke_Grenade_shell",
	"3Rnd_Smoke_Grenade_shell",
	"1Rnd_SmokeRed_Grenade_shell",
	"3Rnd_SmokeRed_Grenade_shell",
	"1Rnd_SmokeGreen_Grenade_shell",
	"3Rnd_SmokeGreen_Grenade_shell",
	"1Rnd_SmokeYellow_Grenade_shell",
	"3Rnd_SmokeYellow_Grenade_shell",
	"1Rnd_SmokePurple_Grenade_shell",
	"3Rnd_SmokePurple_Grenade_shell",
	"1Rnd_SmokeBlue_Grenade_shell",
	"3Rnd_SmokeBlue_Grenade_shell",
	"1Rnd_SmokeOrange_Grenade_shell",
	"3Rnd_SmokeOrange_Grenade_shell"
] + whitelisted_from_arsenal;

// UAVs Terminal
private _blacklisted_uavs_terminal = [
	"B_UavTerminal",
	"O_UavTerminal",
	"I_UavTerminal",
	"I_E_UavTerminal",
	"C_UavTerminal"
] - [uavs_terminal_typename];

GRLIB_blacklisted_from_arsenal append _blacklisted_uavs_terminal;
GRLIB_whitelisted_from_arsenal append [uavs_terminal_typename];
