/*
 * TRANSLATION FILE (ENGLIGH)
 *
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 *
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "吊挂物体";
STR_R3F_LOG_action_heliporter_fait = "物体 ""%1"" 已附上.";
STR_R3F_LOG_action_heliport_larguer = "放下物体";
STR_R3F_LOG_action_heliport_paradrop = "Parachute the object";
STR_R3F_LOG_action_heliport_larguer_fait = "物体 ""%1"" 已放下.";
STR_R3F_LOG_action_heliport_attente = "吊挂中... (%1)";
STR_R3F_LOG_action_heliport_echec_attente = "中止吊挂! 在挂钩过程中保持悬停。";

STR_R3F_LOG_action_deplacer_objet = "拿起 ""%1""";
STR_R3F_LOG_action_relacher_objet = "释放 ""%1""";
STR_R3F_LOG_action_aligner_pente = "调整坡度";
STR_R3F_LOG_action_aligner_sol = "适应地面";
STR_R3F_LOG_action_aligner_horizon = "水平调整";
STR_R3F_LOG_action_tourner = "向左/向右旋转 (X / C 键)";
STR_R3F_LOG_action_rapprocher = "更近/更远 (F / R 键)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "携带此物品时，您不能上车！";

STR_R3F_LOG_action_charger_deplace = "装载车辆";
STR_R3F_LOG_action_selectionner_objet_charge = "装载 ""%1"" 中...";
STR_R3F_LOG_action_charger_selection = "... 装载 ""%1""";
STR_R3F_LOG_action_selectionner_objet_fait = "现在选择目的地 ""%1""...";
STR_R3F_LOG_action_charger_en_cours = "正在装载...";
STR_R3F_LOG_action_charger_fait = "物体 ""%1"" 已经被装载进 ""%2"".";
STR_R3F_LOG_action_charger_pas_assez_de_place = "该车辆中没有足够的空间容纳这个物体!";

STR_R3F_LOG_action_remorquer_direct = "牵引 ""%1""";
STR_R3F_LOG_action_remorquer_deplace = "拖曳物体";
STR_R3F_LOG_action_detacher = "取消拖曳";
STR_R3F_LOG_action_detacher_fait = "物体已分离。";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "只有飞行员可以分离该物体.";

STR_R3F_LOG_action_contenu_vehicule = "查看载具库存";
STR_R3F_LOG_action_decharger_en_cours = "正在卸载...";
STR_R3F_LOG_action_decharger_fait = "物体 ""%1"" 已经从载具中卸载.";
STR_R3F_LOG_action_decharger_deja_fait = "该对象已被卸载！";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "一旦释放，该对象将不再可以手动移动。<br/>你确认继续吗？";

STR_R3F_LOG_action_ouvrir_usine = "打开创造工厂";
STR_R3F_LOG_action_creer_en_cours = "创造中...";
STR_R3F_LOG_action_creer_fait = "物体 ""%1"" 已被建造.";
STR_R3F_LOG_action_creer_pas_assez_credits = "工厂没有足够的弹药来制造该物体.";
STR_R3F_LOG_action_revendre_usine_direct = "将 ""%1"" 送回工厂";
STR_R3F_LOG_action_revendre_usine_deplace = "送回工厂";
STR_R3F_LOG_action_revendre_usine_selection = "... 将送回工厂";
STR_R3F_LOG_action_revendre_en_cours = "正在送回工厂...";
STR_R3F_LOG_action_revendre_fait = "物体 ""%1"" 已被送回工厂.";
STR_R3F_LOG_action_revendre_decharger_avant = "当该库存不为空时，你不能将其送回!";

STR_R3F_LOG_mutex_action_en_cours = "当前操作尚未完成!";
STR_R3F_LOG_joueur_dans_objet = "对象中有一个玩家 ""%1"" !";
STR_R3F_LOG_objet_en_cours_transport = "物体 ""%1"" 已经在运输途中了 !";
STR_R3F_LOG_objet_remorque_en_cours = "不可能，因为这个物体 ""%1"" 拖着另一个物体!";
STR_R3F_LOG_trop_loin = "不可能，因为这个物体 ""%1"" 距离太远了!";

STR_R3F_LOG_dlg_CV_titre = "载具库存";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "装载中 : %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "卸载";
STR_R3F_LOG_dlg_CV_btn_fermer = "取消";

STR_R3F_LOG_dlg_LO_titre = "创建工厂";
STR_R3F_LOG_dlg_LO_credits_restants = "剩余弹药 : %1";
STR_R3F_LOG_dlg_LO_btn_creer = "创建";
STR_R3F_LOG_dlg_LO_btn_fermer = "取消";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "资产";
STR_R3F_LOG_nom_fonctionnalite_side = "支线";
STR_R3F_LOG_nom_fonctionnalite_places = "安置";
STR_R3F_LOG_nom_fonctionnalite_passif = "有可能 :";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "被玩家移动";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "举起";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "拖拉";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "运输";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "负荷成本 %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "它可以 :";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "举起";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "拖拉";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "运输";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "最大加载 %1";

STR_R3F_LOG_deverrouillage_en_cours = "解锁中... (%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "取消解锁! 请在倒计时期间保持瞄准物体。";
STR_R3F_LOG_deverrouillage_succes_attente = "对象已解锁";
STR_R3F_LOG_action_deverrouiller = "解锁 ""%1""";
STR_R3F_LOG_action_deverrouiller_impossible = "对象已锁定";