/*
 * TRANSLATION FILE (RUSSIAN)
 *
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 *
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "Поднять объект";
STR_R3F_LOG_action_heliporter_fait = "Объект ""%1"" закреплен.";
STR_R3F_LOG_action_heliport_larguer = "Сбросить объект";
STR_R3F_LOG_action_heliport_paradrop = "Парашютировать объект";
STR_R3F_LOG_action_heliport_larguer_fait = "Объект ""%1"" сброшен.";
STR_R3F_LOG_action_heliport_attente = "Закрепление... (%1)";
STR_R3F_LOG_action_heliport_echec_attente = "Подъем отменен! Оставайтесь над объектом идет подъем.";

STR_R3F_LOG_action_deplacer_objet = "Взять ""%1""";
STR_R3F_LOG_action_relacher_objet = "Отпустить ""%1""";
STR_R3F_LOG_action_aligner_pente = "Регулировка наклона";
STR_R3F_LOG_action_aligner_sol = "Привязка к земле";
STR_R3F_LOG_action_aligner_horizon = "Установить горизонально";
STR_R3F_LOG_action_tourner = "Повернуть налево/вправо (X / C клавиши)";
STR_R3F_LOG_action_rapprocher = "Ближе/далее (F / R клавиши)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "Вы не можете попасть в транспорт пока несете этот объект!";

STR_R3F_LOG_action_charger_deplace = "Загрузка в транспорт";
STR_R3F_LOG_action_selectionner_objet_charge = "Загрузка ""%1"" в...";
STR_R3F_LOG_action_charger_selection = "... Загрузка в ""%1""";
STR_R3F_LOG_action_selectionner_objet_fait = "Теперь выберите точку назначения для ""%1""...";
STR_R3F_LOG_action_charger_en_cours = "Выполняется загрузка...";
STR_R3F_LOG_action_charger_fait = "Этот объект ""%1"" был загружен в ""%2"".";
STR_R3F_LOG_action_charger_pas_assez_de_place = "Для этого объекта не хватает свободного места в транспорте!";

STR_R3F_LOG_action_remorquer_direct = "Буксировать ""%1""";
STR_R3F_LOG_action_remorquer_deplace = "Буксировать об'єкт";
STR_R3F_LOG_action_detacher = "Перестать буксировать";
STR_R3F_LOG_action_detacher_fait = "Объект больше не буксируется";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "Только пилот может выделить этот объект.";

STR_R3F_LOG_action_contenu_vehicule = "Просмотреть содержимое транспорта";
STR_R3F_LOG_action_decharger_en_cours = "Выполняется выгрузка...";
STR_R3F_LOG_action_decharger_fait = "Объект ""%1"" был выгружен из транспорта.";
STR_R3F_LOG_action_decharger_deja_fait = "Объект уже был загружен !";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "После освобождения этот объект больше нельзя будет переместить вручную.<br/>Подтверждаете действие?";

STR_R3F_LOG_action_ouvrir_usine = "Открыть фабрику";
STR_R3F_LOG_action_creer_en_cours = "Выполняется создание...";
STR_R3F_LOG_action_creer_fait = "Объект ""%1"" был создан.";
STR_R3F_LOG_action_creer_pas_assez_credits = "На фабрике не хватает кредитов для создания этого объекта.";
STR_R3F_LOG_action_revendre_usine_direct = "Вернуть ""%1"" на фабрику";
STR_R3F_LOG_action_revendre_usine_deplace = "Вернуть на фабрику";
STR_R3F_LOG_action_revendre_usine_selection = "... вернуть на фабрику";
STR_R3F_LOG_action_revendre_en_cours = "Возврат на фабрику...";
STR_R3F_LOG_action_revendre_fait = "Объект ""%1"" был возвращен на фабрику.";
STR_R3F_LOG_action_revendre_decharger_avant = "Вы не можете вернуть это до тех пор, пока не выгружен груз из него!";

STR_R3F_LOG_mutex_action_en_cours = "Текущая операция не завершена!";
STR_R3F_LOG_joueur_dans_objet = "В объекте находится игрок""%1"" !";
STR_R3F_LOG_objet_en_cours_transport = "Объект ""%1"" уже в транзите!";
STR_R3F_LOG_objet_remorque_en_cours = "Не возможно, потому что объект ""%1"" буксирует другой объект!";
STR_R3F_LOG_trop_loin = "Не возможно, потому что ""%1"" слишком далеко!";

STR_R3F_LOG_dlg_CV_titre = "Содержимое транспорта";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "Загрузка: %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "ВЫГРУЗИТЬ";
STR_R3F_LOG_dlg_CV_btn_fermer = "ОТМЕНИТЬ";

STR_R3F_LOG_dlg_LO_titre = "Фабрика";
STR_R3F_LOG_dlg_LO_credits_restants = "Осталось кредитов: %1";
STR_R3F_LOG_dlg_LO_btn_creer = "СОЗДАТЬ";
STR_R3F_LOG_dlg_LO_btn_fermer = "ОТМЕНИТЬ";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "Свойства";
STR_R3F_LOG_nom_fonctionnalite_side = "Сторона";
STR_R3F_LOG_nom_fonctionnalite_places = "Рассадка";
STR_R3F_LOG_nom_fonctionnalite_passif = "Может быть:";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "Перемещено игроком";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "Поднято";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "Отбуксировано";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "Перевезено";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "стоимость загрузки %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "Может:";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "Поднимать";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "Буксировать";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "Перевозить";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "максимальная загрузка %1";

STR_R3F_LOG_deverrouillage_en_cours = "Разблокирование... (%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "Разблокировка отменена! Удерживайте объект в поле зрения в процессе разблокирования.";
STR_R3F_LOG_deverrouillage_succes_attente = "Объект разблокирован.";
STR_R3F_LOG_action_deverrouiller = "Разблокировать ""%1""";
STR_R3F_LOG_action_deverrouiller_impossible = "Объект заблокирован";
