/*
 * TRANSLATION FILE (RUSSIAN)
 *
 * Alternative to stringtable.csv which is simpler to install for the mission maker.
 * The token ""%1"" represents a dynamic value generated by the scripts, like a vehicle name.
 *
 * Alternative au stringtable.csv qui est plus simple à installer pour le créateur de mission.
 * Le mot-clé ""%1"" représente une valeur dynamique fournie par les scripts, comme par exemple un nom de véhicule.
 */

STR_R3F_LOG_action_heliporter = "Підняти об'єкт";
STR_R3F_LOG_action_heliporter_fait = "Об'єкт ""%1"" підєднано.";
STR_R3F_LOG_action_heliport_larguer = "Скинути об'єкт";
STR_R3F_LOG_action_heliport_paradrop = "Parachute the object";
STR_R3F_LOG_action_heliport_larguer_fait = "Обєкт ""%1"" скинуто.";
STR_R3F_LOG_action_heliport_attente = "Причеплення... (%1)";
STR_R3F_LOG_action_heliport_echec_attente = "Підйом відмінено ! Залишайтися наб обєктом доки підіймаєте.";

STR_R3F_LOG_action_deplacer_objet = "Взяти ""%1""";
STR_R3F_LOG_action_relacher_objet = "Відпустити ""%1""";
STR_R3F_LOG_action_aligner_pente = "Регулювання нахилу";
STR_R3F_LOG_action_aligner_sol = "Прив'язка до землі";
STR_R3F_LOG_action_aligner_horizon = "Встановити горизонально";
STR_R3F_LOG_action_tourner = "Повернути ліворуч/праворуч (X / C клавіші)";
STR_R3F_LOG_action_rapprocher = "Ближче/далі (F / R клавіші)";
STR_R3F_LOG_ne_pas_monter_dans_vehicule = "Ви не можете потрапити до транспорту доки несете цей об'єкт !";

STR_R3F_LOG_action_charger_deplace = "Завантаження у транспорт";
STR_R3F_LOG_action_selectionner_objet_charge = "Завантажити ""%1"" до...";
STR_R3F_LOG_action_charger_selection = "... Завантаження до ""%1""";
STR_R3F_LOG_action_selectionner_objet_fait = "Тепер оберіть точку призначення для ""%1""...";
STR_R3F_LOG_action_charger_en_cours = "Виконується завантаження...";
STR_R3F_LOG_action_charger_fait = "Цей об'єкт ""%1"" було завантажено до ""%2"".";
STR_R3F_LOG_action_charger_pas_assez_de_place = "Для цього об'єкта не вистачає вільного місця у транспорті !";

STR_R3F_LOG_action_remorquer_direct = "Буксирувати ""%1""";
STR_R3F_LOG_action_remorquer_deplace = "Буксирувати об'єкт";
STR_R3F_LOG_action_detacher = "Перестати буксирувати";
STR_R3F_LOG_action_detacher_fait = "Об'єкт більше не буксирується.";
STR_R3F_LOG_action_detacher_impossible_pour_ce_vehicule = "Тільки пілот може від'єтнати цей об'єкт.";

STR_R3F_LOG_action_contenu_vehicule = "Переглянути вміст транспорту";
STR_R3F_LOG_action_decharger_en_cours = "Виконується вивантаження...";
STR_R3F_LOG_action_decharger_fait = "Об'єкт ""%1"" було вивантажено з транспорту.";
STR_R3F_LOG_action_decharger_deja_fait = "Обє'кт вже було завантажено !";
STR_R3F_LOG_action_decharger_deplacable_exceptionnel = "Після звільнення цей об'єкт більше не можна буде перемістити вручну.<br/>Підтверджуєте дію ?";

STR_R3F_LOG_action_ouvrir_usine = "Відкрити фабрику";
STR_R3F_LOG_action_creer_en_cours = "Виконується створення...";
STR_R3F_LOG_action_creer_fait = "Об'єкт ""%1"" було створено.";
STR_R3F_LOG_action_creer_pas_assez_credits = "На фабриці не вистачає кредитів для створення цього об'єкта.";
STR_R3F_LOG_action_revendre_usine_direct = "Повернути ""%1"" на фабрику";
STR_R3F_LOG_action_revendre_usine_deplace = "Повернути на фабрику";
STR_R3F_LOG_action_revendre_usine_selection = "... повернути на фабрику";
STR_R3F_LOG_action_revendre_en_cours = "Повернення на фабрику...";
STR_R3F_LOG_action_revendre_fait = "Об'єкт ""%1"" було повернуто на фабрику.";
STR_R3F_LOG_action_revendre_decharger_avant = "Ви не можете повернути це доки не вивантажено вантаж з нього !";

STR_R3F_LOG_mutex_action_en_cours = "Поточна операцію на завершена !";
STR_R3F_LOG_joueur_dans_objet = "В об'єкті знаходиться гравець ""%1"" !";
STR_R3F_LOG_objet_en_cours_transport = "Обєкт ""%1"" вже в транзиті !";
STR_R3F_LOG_objet_remorque_en_cours = "Не можливо, тому що об'єкт ""%1"" буксирує інший об'єкт !";
STR_R3F_LOG_trop_loin = "Не можливо, тому що ""%1"" занадто далеко !";

STR_R3F_LOG_dlg_CV_titre = "Вміст транспорту";
STR_R3F_LOG_dlg_CV_capacite_vehicule = "Завантаження : %1/%2";
STR_R3F_LOG_dlg_CV_btn_decharger = "ВИВАНТАЖИТИ";
STR_R3F_LOG_dlg_CV_btn_fermer = "ВІДМІНИТИ";

STR_R3F_LOG_dlg_LO_titre = "Фабрика";
STR_R3F_LOG_dlg_LO_credits_restants = "Залишилось кредитів : %1";
STR_R3F_LOG_dlg_LO_btn_creer = "СТВОРИТИ";
STR_R3F_LOG_dlg_LO_btn_fermer = "ВІДМІНИТИ";

STR_R3F_LOG_nom_fonctionnalite_proprietes = "Властивості";
STR_R3F_LOG_nom_fonctionnalite_side = "Сторона";
STR_R3F_LOG_nom_fonctionnalite_places = "Сидить";
STR_R3F_LOG_nom_fonctionnalite_passif = "Може :";
STR_R3F_LOG_nom_fonctionnalite_passif_deplace = "Переміщати гравців";
STR_R3F_LOG_nom_fonctionnalite_passif_heliporte = "Піднімати";
STR_R3F_LOG_nom_fonctionnalite_passif_remorque = "Буксирувати";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte = "Перевозити";
STR_R3F_LOG_nom_fonctionnalite_passif_transporte_capacite = "завантаження коштує %1";
STR_R3F_LOG_nom_fonctionnalite_actif = "Може :";
STR_R3F_LOG_nom_fonctionnalite_actif_heliporte = "Піднімати";
STR_R3F_LOG_nom_fonctionnalite_actif_remorque = "Буксирувати";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte = "Перевозити";
STR_R3F_LOG_nom_fonctionnalite_actif_transporte_capacite = "максимальне завантаження %1";

STR_R3F_LOG_deverrouillage_en_cours = "Розблокування... (%1)";
STR_R3F_LOG_deverrouillage_echec_attente = "Розблокування відмінено ! Утримуйте об'єкт у полі зору протягом лічильника.";
STR_R3F_LOG_deverrouillage_succes_attente = "Об'єкт розблоковано.";
STR_R3F_LOG_action_deverrouiller = "Розлокувати ""%1""";
STR_R3F_LOG_action_deverrouiller_impossible = "Об'єкт заблоковано";
