/*
    Killah Potatoes Cratefiller v1.2.0 dialog defines

    File: defines.hpp
    Author: Dubjunk - https://github.com/KillahPotatoes
    Date: 2019-08-06
    Last Update: 2020-10-09
    License: GNU General Public License v3.0 - https://www.gnu.org/licenses/gpl-3.0.html

    Description:
        Common defines for cratefiller UI elements
*/

#define KP_CRATEFILLER_IDC_DIALOG                 758067

#define KP_CRATEFILLER_IDC_GROUPOVERVIEW          687400
#define KP_CRATEFILLER_IDC_COMBOGROUPS            687401
#define KP_CRATEFILLER_IDC_COMBOPLAYERS           687402
#define KP_CRATEFILLER_IDC_MAINWEAPON             687403
#define KP_CRATEFILLER_IDC_HANDGUN                687404
#define KP_CRATEFILLER_IDC_SECONDARYWEAPON        687405

#define KP_CRATEFILLER_IDC_BUTTONOVERVIEW         687406

#define KP_CRATEFILLER_IDC_COMBOCRATE             687407
#define KP_CRATEFILLER_IDC_COMBOSTORAGE           687408
#define KP_CRATEFILLER_IDC_BUTTONSPAWNCRATE       687409
#define KP_CRATEFILLER_IDC_BUTTONDELETECRATE      687410

#define KP_CRATEFILLER_IDC_COMBOEQUIPMENT         687411
#define KP_CRATEFILLER_IDC_COMBOWEAPONS           687412
#define KP_CRATEFILLER_IDC_SEARCHBAR              687413
#define KP_CRATEFILLER_IDC_BUTTONLEFTEQUIPMENT    687414
#define KP_CRATEFILLER_IDC_BUTTONRIGHTEQUIPMENT   687415
#define KP_CRATEFILLER_IDC_EQUIPMENTLIST          687416

#define KP_CRATEFILLER_IDC_EXPORTNAME             687417
#define KP_CRATEFILLER_IDC_IMPORTNAME             687418
#define KP_CRATEFILLER_IDC_BUTTONLEFTINVENTORY    687419
#define KP_CRATEFILLER_IDC_BUTTONRIGHTINVENTORY   687420
#define KP_CRATEFILLER_IDC_INVENTORYLIST          687421
#define KP_CRATEFILLER_IDC_BUTTONCLEARINVENTORY   687422

#define KP_CRATEFILLER_IDC_PROGRESSBAR            687423
