// Initalize Side
GRLIB_arsenal_side = WEST;

//Blacklist Items
blacklisted_bag = [];

blacklisted_weapon = [
	"U_O_CombatUniform_ocamo",
	"U_O_CombatUniform_oucamo",
	"U_O_OfficerUniform_ocamo",
	"U_O_PilotCoveralls",
	"U_O_SpecopsUniform_ocamo",
	"U_O_Wetsuit",
	"U_O_T_Soldier_F",
	"U_O_T_FullGhillie_tna_F",
	"U_O_T_Officer_F",
	"U_O_V_Soldier_Viper_F",
	"U_O_V_Soldier_Viper_hex_F",
	"CsatU_Berezka",
	"CsatU_BerezkaY",
	"CsatU_blue",
	"CsatU_EMR",
	"CsatU_Green",
	"CsatU_khaki",
	"CsatU_mtp",
	"CsatU_TigerJ",
	"CsatU_type07u",
	"H_HelmetSpecO_blk",
	"H_HelmetSpecO_ocamo",
	"H_HelmetLeaderO_ocamo",
	"H_HelmetLeaderO_oucamo",
	"H_HelmetCrew_O",
	"H_ParadeDressCap_01_CSAT_F",
	"CSAT_helmet_blue",
	"CSAT_helmet_EMR",
	"CSAT_helmet_Green",
	"CSAT_helmet_khaki",
	"CSAT_helmet_mtp",
	"CSAT_helmet_TigerJ",
	"CSAT_helmet_Type07U",
	"H_MilCap_ocamo",
	"H_PilotHelmetFighter_O",
	"H_HelmetO_ocamo",
	"H_HelmetO_oucamo",
	"H_HelmetSpecO_ghex_F",
	"H_HelmetLeaderO_ghex_F",
	"H_MilCap_ghex_F",
	"H_HelmetO_ghex_F",
	"H_HelmetO_ViperSP_ghex_F",
	"H_HelmetO_ViperSP_hex_F",
	"H_Beret_CSAT_01_F",
	"U_O_FullGhillie_ard",
	"U_O_FullGhillie_lsh",
	"U_O_FullGhillie_sard",
	"U_I_Protagonist_VR",
	"U_C_Protagonist_VR",
	"U_O_Protagonist_VR",
	"U_B_Protagonist_VR",
	"V_CSAT",
	"V_CSAT_R",
	"U_O_T_Sniper_F",
	"U_O_GhillieSuit",
	"U_O_officer_noInsignia_hex_F"
];

GRLIB_whitelisted_from_arsenal = [];
