// position, generated by:
/*
 _object = "phonebooth_";  //"atm_"
 _res = []; 
 private _pos = getArray(configFile >> "CfgWorlds" >> worldName >> "centerPosition"); 
 { 
  if (_x distance2D lhd > 1000) then { 
    if (str _x find _object > 0) then { _res pushback (getPos _x) }; 
  }; 
} foreach nearestobjects [_pos, [], worldSize / 2]; 
systemchat str (count _res); 
copyToClipboard str _res;


//executed in console, result in clipboard.
*/
GRLIB_Marker_ATM =[
];

GRLIB_Marker_SRV = [

];