GRLIB_save_key = "GREUH_LIBERATION_Kujari_saveGame_PSK";
// change this value if you want different saveGames on different map
GRLIB_side_resistance = resistance;
GRLIB_side_civilian = civilian;
GRLIB_respawn_marker = "respawn_west";
GRLIB_sector_size = 600;
GRLIB_capture_size = 400;
GRLIB_radiotower_size = 2500;
GRLIB_spawn_min = 2000;
GRLIB_spawn_max = 4000;
GRLIB_recycling_percentage = 1.00;
GRLIB_endgame = 0;
GRLIB_vulnerability_timer = 1200;
GRLIB_defended_buildingPos_part = 0.5;
GRLIB_sector_military_value = 3;
GRLIB_secondary_objective_impact = 0.4;
GRLIB_blufor_cap = 10 * GRLIB_unitcap;
GRLIB_sector_cap = 120 * GRLIB_unitcap;
GRLIB_battlegroup_cap = 75 * GRLIB_unitcap;
GRLIB_patrol_cap = 75 * GRLIB_unitcap;
GRLIB_battlegroup_size = 7;
GRLIB_civilians_amount = 2 * GRLIB_civilian_activity;
GRLIB_fob_range = 450;
GRLIB_surrender_chance = 80;
GRLIB_secondary_missions_costs = [ 50,5 ];
GRLIB_halo_altitude = 2000;
GRLIB_civ_killing_penalty = 0;
GRLIB_squad_size_bonus = 0;
GRLIB_perm_ban = -1000000;
GRLIB_perm_inf = -45;
GRLIB_perm_log = 400;
GRLIB_perm_tank = 800;
GRLIB_perm_air = 1200;
GRLIB_perm_max = 1600;
GRLIB_date_year = 2022;
GRLIB_date_month = 7;
GRLIB_date_day = 30;
GRLIB_nights_start = 21;
GRLIB_nights_stop = 4;
GREUH_start_ammo = 400;

GRLIB_blufor_cap = 64;
// defines if everyone gets ammo from sector liberations
Sector_ammo_for_all = false;

// don't forget that the human commander manages those, not the server
GRLIB_offload_diag = false;

// NRE_Key = 199;
MGR_Key = 19;

// TFAR channel
tfar_channel = "╠-● Ingame [TFAR]";

// gain and punishment
respawn_ammo = 100; // +/- is conditional
opfor_kill_score = 1;
opfor_kill_ammo = 1;
opfor_kill_score_infantry = 1;
opfor_kill_ammo_infantry = 5;
kamikaze_kill_score = 5;
kamikaze_kill_ammo = 25;
civkill_score = 0;
civkill_ammo = -100;
tkill_score = -4;
tkill_ammo = -40;
tkill_script = false;
tk_active = true; //NEW Tkillscript with dialog

// Only use by 2 dividable numbers
box_recycle_value = 40;
// Increases the ammo for logistics and decreasese the ammo for everyone
logistics_ammo_increase = true;

prisoner_intel = 15;
prisoner_score = 10;
prisoner_ammo = 50;

// Building Penalty
building_penalty_isActive = false;

// Global arsenal
global_arsenal = true;

// true to activate factions selection
FAC_MSU_ACTIVE = false;

MSU_Med_Div = 4;
MSU_Eng_Div = 6;

// Do not allow air vehicles to trigger zones. 
air_cannot_trigger_on = true;

//Differenced Ammo income 
fallback_income = 50;
income_sectors_bigtown = 50;
income_sectors_capture = 50;
income_sectors_military = 50;
income_sectors_factory = 50;
income_sectors_tower = 50;

// AI Leaders have automaticly radios
AI_leader_radio = false;

// HC
hc_battlegroup_on = false;

skill_scan = false;
skill_parachuters = 1;
skill_air_vehicles_planes = 1;
skill_air_vehicles_helicopters = 1;
skill_ground_vehicles = 1;

limit_hc_gr = true;
// Readiness Increase from towns
readiness_calc_bg_town = true;
readiness_calc_sm_town = true;
limit_readiness = true;
fob_hunting_readiness = 40;

//Battlegroup sleeping (divided with csat aggressivity)
bg_sleeptimer = 1000; 
sector_reinforcement = true;
limit_bg_dist = 4000; 
reinforce_spawn_min = 1000;
unload_distance = 400;

// Deactivate HC spawning
hc_spawn_off = false;
hc_spawn_towns = true;
hc_spawn_patrol = false;

//Datalink Options
force_datalink = true;
force_sensorTarget_opfor = false;

//Enemy IEDs
ied_enemy_sector = ["rhsusf_mine_m49a1_3m_module","ModuleMine_ATMine_F","ModuleMine_SLAMDirectionalMine_F","rhsusf_mine_m14_module","rhsusf_mine_m19_module"];

// AI Limit
ai_limit = 3;
ai_limiter_on = true;
// ai skill
ai_skill = 9;
ai_value = 35; // buildable ai price

//Medic restrictions
support_medic_restriction = false;


// Prices for blufor vehicle tiers
light_vehicle_price_hmg = 220;
light_vehicle_price_gmg = 250;
heavy_vehicle_price_tank = 500;
heavy_vehicle_price_tank_light = 1000;
heavy_vehicle_price_tank_heavy = 1500;
logistic_air_vehicle_price = 250;
logistic_ground_vehicle_price = 200;

light_vehicle_price_tier_1 = 50;
light_vehicle_price_tier_2 = 75;
light_vehicle_price_tier_3 = 100;
light_vehicle_price_tier_4 = 125;
light_vehicle_price_tier_5 = 150;
light_vehicle_price_tier_6 = 175;
light_vehicle_price_tier_7 = 200;
light_vehicle_price_tier_8 = 225;
light_vehicle_price_tier_9 = 250;
light_vehicle_price_tier_10 = 275;
light_vehicle_price_tier_11 = 300;
light_vehicle_price_tier_12 = 350;
strong_light_vehicle_price_tier_1 = 100;
strong_light_vehicle_price_tier_2 = 125;
strong_light_vehicle_price_tier_3 = 150;
strong_light_vehicle_price_tier_4 = 175;
strong_light_vehicle_price_tier_5 = 200;
strong_light_vehicle_price_tier_6 = 225;
strong_light_vehicle_price_tier_7 = 250;
strong_light_vehicle_price_tier_8 = 275;
strong_light_vehicle_price_tier_9 = 300;
strong_light_vehicle_price_tier_10 = 325;
strong_light_vehicle_price_tier_11 = 350;
strong_light_vehicle_price_tier_12 = 375;
strong_light_vehicle_price_tier_13 = 400;
strong_light_vehicle_price_tier_14 = 425;
strong_light_vehicle_price_tier_15 = 450;
heavy_vehicle_price_tier_1 = 250;
heavy_vehicle_price_tier_2 = 275;
heavy_vehicle_price_tier_3 = 300;
heavy_vehicle_price_tier_4 = 325;
heavy_vehicle_price_tier_5 = 350;
heavy_vehicle_price_tier_6 = 375;
heavy_vehicle_price_tier_7 = 400;
heavy_vehicle_price_tier_8 = 450;
heavy_vehicle_price_tier_9 = 500;
heavy_vehicle_price_tier_10 = 550;
heavy_vehicle_price_tier_11 = 600;
heavy_vehicle_price_tier_12 = 700;
heavy_vehicle_price_tier_13 = 800;
heavy_vehicle_price_tier_14 = 1000;
heavy_vehicle_price_tier_15 = 1250;
heavy_vehicle_price_tier_16 = 1500;
heavy_vehicle_price_tier_17 = 1750;
strong_heavy_vehicle_price_tier_1 = 1000;
strong_heavy_vehicle_price_tier_2 = 1250;
strong_heavy_vehicle_price_tier_3 = 1500;
strong_heavy_vehicle_price_tier_4 = 1750;
strong_heavy_vehicle_price_tier_5 = 2000;
strong_heavy_vehicle_price_tier_6 = 5000;
strong_heavy_vehicle_price_tier_7 = 7500;
air_vehicle_price_tier_1 = 250;
air_vehicle_price_tier_2 = 275;
air_vehicle_price_tier_3 = 300;
air_vehicle_price_tier_4 = 350;
air_vehicle_price_tier_5 = 400;
air_vehicle_price_tier_6 = 500;
air_vehicle_price_tier_7 = 550;
air_vehicle_price_tier_8 = 800;
air_vehicle_price_tier_9 = 900;
air_vehicle_price_tier_10 = 1000;
air_vehicle_price_tier_11 = 1300;
air_vehicle_price_tier_12 = 1500;
air_vehicle_price_tier_13 = 1800;
air_vehicle_price_tier_14 = 2000;
air_vehicle_price_tier_15 = 4000;
fast_air_vehicle_price_tier_1 = 350;
fast_air_vehicle_price_tier_2 = 1000;
fast_air_vehicle_price_tier_3 = 1250;
fast_air_vehicle_price_tier_4 = 1500;
fast_air_vehicle_price_tier_5 = 1750;
fast_air_vehicle_price_tier_6 = 2000;
fast_air_vehicle_price_tier_7 = 2250;
fast_air_vehicle_price_tier_8 = 2500;
fast_air_vehicle_price_tier_9 = 2750;
fast_air_vehicle_price_tier_10 = 3000;
logistic_ground_vehicle_price_tier_1 = 250;
logistic_ground_vehicle_price_tier_2 = 300;
logistic_ground_vehicle_price_tier_3 = 400;
logistic_ground_vehicle_price_tier_4 = 450;
logistic_ground_vehicle_price_tier_5 = 500;
logistic_ground_vehicle_price_tier_6 = 550;

moderators = [
    "76561197997804176", // slotzi
    "76561198019854511", // Voltaren
    "76561198094301584", // Devin
    "76561198132964589", // Sound_wave
    "76561198043617179", // Manta 
    "76561198100256441",
    "76561198057808323",
    "76561197993044168"
];


items_allFac = [
    "U_B_FullGhillie_lsh",
    "U_B_FullGhillie_sard",
    "U_B_GhillieSuit",
    "U_B_T_FullGhillie_tna_F",
    "U_B_T_Sniper_F",
    "U_B_Wetsuit",
    "U_B_pilotCoveralls",
    "H_pilotHelmetFighter_B",
    "H_pilotHelmetHeli_B",
    "V_RebreatherB"
];


item_whitelist = [
    "ACE_HuntIR_M203",
    "CUP_Stinger_M",
    "KKiv_Mag_APFSDS"
];


item_blacklist =
[
    "CUP_arifle_ACRC_snw_556",
    "CUP_arifle_ACRC_snw_68",
    "CUP_arifle_ACRC_tan_556",
    "CUP_arifle_ACRC_tan_68",
    "CUP_arifle_ACRC_wdl_556",
    "CUP_arifle_ACRC_wdl_68",
    "CUP_arifle_ACRC_EGLM_blk_556",
    "CUP_arifle_ACRC_EGLM_blk_68",
    "CUP_arifle_ACRC_EGLM_snw_556",
    "CUP_arifle_ACRC_EGLM_snw_68",
    "CUP_arifle_ACRC_EGLM_tan_556",
    "CUP_arifle_ACRC_EGLM_tan_68",
    "CUP_arifle_ACRC_EGLM_wdl_556",
    "CUP_arifle_ACRC_EGLM_wdl_68",
    "CUP_arifle_ACR_blk_556",
    "CUP_arifle_ACR_blk_68",
    "CUP_arifle_ACR_snw_556",
    "CUP_arifle_ACR_snw_68",
    "CUP_arifle_ACR_tan_556",
    "CUP_arifle_ACR_tan_68",
    "CUP_arifle_ACR_wdl_556",
    "CUP_arifle_ACR_wdl_68",
    "CUP_arifle_ACR_DMR_blk_556",
    "CUP_arifle_ACR_DMR_blk_68",
    "CUP_arifle_ACR_DMR_snw_556",
    "CUP_arifle_ACR_DMR_snw_68",
    "CUP_arifle_ACR_DMR_tan_556",
    "CUP_arifle_ACR_DMR_tan_68",
    "CUP_arifle_ACR_DMR_wdl_556",
    "CUP_arifle_ACR_DMR_wdl_68",
    "CUP_arifle_ACR_EGLM_blk_556",
    "CUP_arifle_ACR_EGLM_blk_68",
    "CUP_arifle_ACR_EGLM_snw_556",
    "CUP_arifle_ACR_EGLM_snw_68",
    "CUP_arifle_ACR_EGLM_tan_556",
    "CUP_arifle_ACR_EGLM_tan_68",
    "CUP_arifle_ACR_EGLM_wdl_556",
    "CUP_arifle_ACR_EGLM_wdl_68",
    "CUP_arifle_M16A1E1",
    "CUP_arifle_M16A1E1GL",
    "CUP_arifle_Colt727",
    "CUP_arifle_Colt727_M203",
    "CUP_srifle_Mosin_Nagant",
    "CUP_srifle_M21",
    "CUP_srifle_M21_ris",
    "CUP_lmg_M249_E1",
    "CUP_arifle_M4A1_MOE_short_black",
    "CUP_arifle_M4A1_MOE_short_desert",
    "CUP_arifle_M4A1_MOE_short_winter",
    "CUP_arifle_M4A1_MOE_short_wdl",
    "CUP_arifle_M4A1_standard_short_black",
    "CUP_arifle_M4A1_standard_short_dsrt",
    "CUP_arifle_M4A1_standard_short_winter",
    "CUP_arifle_M4A1_standard_short_wdl",
    "CUP_arifle_M4A1_MOE_black",
    "CUP_arifle_M4A1_MOE_desert",
    "CUP_arifle_M4A1_MOE_winter",
    "CUP_arifle_M4A1_MOE_wdl",
    "CUP_arifle_M4A1_standard_black",
    "CUP_arifle_M4A1_standard_dsrt",
    "CUP_arifle_M4A1_standard_winter",
    "CUP_arifle_M4A1_standard_wdl",
    "CUP_lmg_M60",
    "CUP_lmg_M60E4_norail",
    "CUP_lmg_M60E4_norail_desert",
    "CUP_lmg_M60E4_norail_jungle",
    "CUP_lmg_M60E4_jungle",
    "CUP_lmg_M60E4",
    "CUP_lmg_M60E4_desert",
    "CUP_lmg_M60E4_wood",
    "CUP_lmg_M60E4_norail_wood",
    "CUP_arifle_Mk20_black",
    "CUP_arifle_Mk20_woodland",
    "CUP_arifle_mk18_black",
    "CUP_arifle_mk18_m203_black",
    "CUP_arifle_OTS14_GROZA_762_Grip",
    "CUP_arifle_OTS14_GROZA_762",
    "CUP_arifle_OTS14_GROZA_762_GL",
    "CUP_smg_p90_black",
    "CUP_smg_p90_olive",
    "CUP_lmg_PKM",
    "CUP_lmg_PKM_B50_vfg",
    "CUP_lmg_PKM_top_rail",
    "CUP_lmg_PKM_top_rail_B50_vfg",
    "CUP_lmg_PKMN",
    "CUP_lmg_Pecheneg_B50_vfg",
    "CUP_lmg_Pecheneg_desert",
    "CUP_lmg_Pecheneg_top_rail_B50_vfg",
    "CUP_lmg_Pecheneg_woodland",
    "CUP_smg_PS90_olive",
    "CUP_srifle_RSASS_Dazzle",
    "CUP_srifle_RSASS_Jungle",
    "CUP_srifle_RSASS_Sand",
    "CUP_srifle_RSASS_Winter",
    "CUP_srifle_RSASS_WDLNet",
    "CUP_srifle_RSASS_WDL",
    "CUP_arifle_IMI_Romat",
    "CUP_arifle_IMI_Romat_railed",
    "CUP_arifle_Sa58Pi",
    "CUP_arifle_DSA_SA58_OSW_Desert",
    "CUP_arifle_DSA_SA58_OSW_VFG_Desert",
    "CUP_arifle_DSA_SA58_OSW_VFG_Sand",
    "CUP_arifle_DSA_SA58_OSW_VFG_Woodland",
    "CUP_arifle_DSA_SA58_OSW_Sand",
    "CUP_arifle_DSA_SA58_OSW_Woodland",
    "CUP_sgun_Saiga12K",
    "CUP_sgun_Saiga12K_top_rail",
    "CUP_SKS",
    "CUP_SKS_rail",
    "CUP_sgun_SPAS12",
    "CUP_arifle_Steyr_Stg58",
    "CUP_arifle_Steyr_Stg58_railed",
    "CUP_arifle_XM8_Carbine",
    "CUP_arifle_XM8_Carbine_FG",
    "CUP_arifle_XM8_Railed",
    "CUP_arifle_XM8_Carbine_GL",
    "CUP_arifle_XM8_Compact",
    "CUP_arifle_XM8_Compact_Rail",
    "CUP_arifle_xm8_SAW",
    "CUP_arifle_xm8_sharpshooter",
    "ffaa_armas_hkag36e",
    "ffaa_armas_hkag36e_tir",
    "ffaa_armas_hkag36k",
    "ffaa_armas_hkag36k_tir",
    "ffaa_armas_hkg36e_normal",
    "ffaa_armas_hkg36e",
    "ffaa_armas_hkmp5a5",
    "ffaa_armas_hkmp5pdw",
    "ffaa_armas_hkmp510a3",
    "ffaa_armas_ump",
    "CUP_arifle_G36A3",
    "CUP_arifle_G36A3_grip",
    "CUP_arifle_G36A3_grip_camo",
    "CUP_arifle_G36A3_grip_hex",
    "CUP_arifle_G36A3_grip_wdl",
    "CUP_arifle_G36A3_hex",
    "CUP_arifle_G36A3_wdl",
    "CUP_arifle_G36A3_camo",
    "CUP_arifle_G36A3_AG36",
    "CUP_arifle_G36A3_AG36_hex",
    "CUP_arifle_G36A3_AG36_wdl",
    "CUP_arifle_G36A3_AG36_camo",
    "CUP_arifle_G36CA3_afg_camo",
    "CUP_arifle_G36CA3_afg_hex",
    "CUP_arifle_G36CA3_afg_wdl",
    "CUP_arifle_G36CA3_grip",
    "CUP_arifle_G36CA3_grip_camo",
    "CUP_arifle_G36CA3_grip_hex",
    "CUP_arifle_G36CA3_grip_wdl",
    "CUP_arifle_G36CA3_hex",
    "CUP_arifle_G36CA3_wdl",
    "CUP_arifle_G36CA3_camo",
    "CUP_arifle_G36E",
    "CUP_arifle_G36E_camo",
    "CUP_arifle_G36E_wdl",
    "CUP_arifle_G36K_KSK",
    "CUP_arifle_G36K_KSK_AFG_camo",
    "CUP_arifle_G36K_KSK_AFG_hex",
    "CUP_arifle_G36K_KSK_camo",
    "CUP_arifle_G36K_KSK_hex",
    "CUP_arifle_G36KA3",
    "CUP_arifle_G36KA3_afg",
    "CUP_arifle_G36KA3_afg_camo",
    "CUP_arifle_G36KA3_afg_hex",
    "CUP_arifle_G36KA3_afg_wdl",
    "CUP_arifle_G36KA3_grip",
    "CUP_arifle_G36KA3_grip_camo",
    "CUP_arifle_G36KA3_grip_hex",
    "CUP_arifle_G36KA3_grip_wdl",
    "CUP_arifle_G36KA3_hex",
    "CUP_arifle_G36KA3_wdl",
    "CUP_arifle_G36KA3_camo",
    "CUP_arifle_G3A3_ris",
    "CUP_arifle_G3A3_ris_black",
    "CUP_arifle_G3A3_ris_vfg",
    "CUP_arifle_G3A3_ris_vfg_black",
    "CUP_arifle_G3A3_modern_ris",
    "CUP_arifle_G3A3_modern_ris_black",
    "CUP_arifle_Galil_556_black",
    "CUP_arifle_Galil_black",
    "CUP_arifle_Galil_SAR_black",
    "CUP_arifle_HK417_12_Desert",
    "CUP_arifle_HK417_12_Wood",
    "CUP_arifle_HK417_12_M203_Desert",
    "CUP_arifle_HK417_12_M203_Wood",
    "CUP_arifle_HK417_12_AG36_Desert",
    "CUP_arifle_HK417_12_AG36_Wood",
    "CUP_arifle_HK417_20_Desert",
    "CUP_arifle_HK417_20_Wood",
    "CUP_srifle_ksvk",
    "CUP_srifle_L129A1_ctrg",
    "CUP_srifle_L129A1_ctrgt",
    "CUP_srifle_L129A1_d",
    "CUP_srifle_L129A1_HG_ctrg",
    "CUP_srifle_L129A1_HG_ctrgt",
    "CUP_srifle_L129A1_HG_d",
    "CUP_srifle_L129A1_HG_w",
    "CUP_srifle_L129A1_w",
    "CUP_srifle_L129A1_HG",
    "CUP_arifle_G3A3_ris_vfg_black",
    "ffaa_armas_p90",
    "ffaa_armas_mg3",
    "hlc_rifle_ACR_SBR_cliffhanger_x15",
    "hlc_rifle_ACR_SBR_black",
    "hlc_rifle_ACR_SBR_green_x15",
    "hlc_rifle_ACR_SBR_tan_x15",
    "hlc_rifle_ACR_SBR_tan",
    "hlc_rifle_ACR_GL_Carb_tan",
    "hlc_rifle_ACR_GL_SBR_tan",
    "hlc_rifle_ACR_GL_mid_tan",
    "hlc_rifle_ACR_MID_black_x15",
    "hlc_rifle_ACR_MID_green_x15",
    "hlc_rifle_ACR_MID_tan_x15",
    "hlc_rifle_ACR_MID_tan",
    "hlc_rifle_ACR68_Squant",
    "hlc_rifle_ACR68_SBR_tan",
    "hlc_rifle_ACR68_GL_Carb_tan",
    "hlc_rifle_ACR68_GL_SBR_tan",
    "hlc_rifle_ACR68_GL_mid_tan",
    "hlc_rifle_ACR68_full_tan",
    "hlc_rifle_ACR68_MID_tan",
    "hlc_rifle_SAMR",
    "hlc_rifle_SAMR_x15",
    "hlc_rifle_amt",
    "CUP_arifle_AKS_Gold",
    "CUP_arifle_FNFAL5060_rhodesian",
    "CUP_arifle_FNFAL5060_desert",
    "CUP_arifle_FNFAL5060_railed_desert",
    "CUP_arifle_FNFAL5060_railed_sand",
    "CUP_arifle_FNFAL5060_railed_woodland",
    "CUP_arifle_FNFAL5060_sand",
    "CUP_arifle_FNFAL5060_woodland",
    "CUP_arifle_FNFAL5061_rhodesian",
    "CUP_arifle_FNFAL_desert",
    "CUP_arifle_FNFAL_railed_desert",
    "CUP_arifle_FNFAL_railed_sand",
    "CUP_arifle_FNFAL_railed_woodland",
    "CUP_arifle_FNFAL_sand",
    "CUP_arifle_FNFAL_woodland",
    "CUP_Famas_F1_Arid",
    "CUP_Famas_F1_Rail_Arid",
    "CUP_Famas_F1_Rail_Wood",
    "CUP_Famas_F1_Wood",
    "hlc_rifle_FAL5000",
    "hlc_rifle_FAL5000_RH_XMAG",
    "hlc_rifle_FAL5000Rail_XMAG",
    "hlc_rifle_FAL5061_XMAG",
    "hlc_rifle_FAL5061Rail_XMAG",
    "hlc_rifle_LAR_XMAG",
    "hlc_lmg_minimi_30Rnd",
    "hlc_lmg_minimi_railed_30Rnd",
    "hlc_lmg_minimipara_long_30Rnd",
    "hlc_lmg_minimipara_30Rnd",
    "hlc_lmg_minimipara_railed_30Rnd",
    "hlc_lmg_minimipara_long_railed_30Rnd",
    "LMG_03_F",
    "hlc_rifle_FN3011_50rnd",
    "hlc_rifle_FN3011_20rnd",
    "hlc_rifle_FN3011Modern_50rnd",
    "hlc_rifle_FN3011Modern_20rnd",
    "hlc_rifle_FN3011Modern_camo_50rnd",
    "hlc_rifle_FN3011Modern_camo_20rnd",
    "hlc_rifle_FN3011Tactical_green_50rnd",
    "hlc_rifle_FN3011Tactical_green_20rnd",
    "hlc_rifle_FN3011Tactical_grey",
    "hlc_rifle_FN3011Tactical_grey_50rnd",
    "hlc_rifle_FN3011Tactical_grey_20rnd",
    "hlc_rifle_FN3011Tactical_20rnd",
    "hlc_rifle_FN3011Tactical_50rnd",
    "hlc_rifle_FN3011Tactical",
    "hlc_rifle_FN3011_WDL_50rnd",
    "hlc_rifle_FN3011_WDL",
    "hlc_rifle_FN3011_WDL_20rnd",
    "hlc_rifle_FN3011Lynx_20rnd",
    "hlc_rifle_FN3011Lynx_50rnd",
    "hlc_rifle_hk51_XMAG",
    "CUP_srifle_G22_blk",
    "CUP_srifle_G22_des",
    "hlc_rifle_416D10_ptato",
    "hlc_rifle_416D10_ptato_x15",
    "hlc_rifle_416D10_RAHG_x15_grip3",
    "hlc_rifle_416D10_RAHG_x15_grip2",
    "hlc_rifle_416D10_RAHG_x15_grip",
    "hlc_rifle_416D10_RAHG_x15",
    "hlc_rifle_416D10_geissele",
    "hlc_rifle_416D10_tan_x15",
    "hlc_rifle_416D10_tan",
    "hlc_rifle_416D10_wdl",
    "hlc_rifle_416D10_wdl_x15",
    "hlc_rifle_416D145_tan",
    "hlc_rifle_416D145_wdl_x15",
    "hlc_rifle_416D145C_x15",
    "hlc_rifle_416D165_x15",
    "hlc_rifle_416D165_tan_x15",
    "hlc_rifle_416D165_wdl_x15",
    "hlc_rifle_416D20_x15",
    "hlc_rifle_416D20_tan_x15",
    "hlc_rifle_416D20_wdl_x15",
    "hlc_rifle_416C_x15",
    "hlc_rifle_bab_x15",
    "hlc_rifle_416N_x15",
    "CUP_lmg_Mk48_wdl",
    "CUP_lmg_Mk48_nohg_wdl",
    "CUP_lmg_Mk48_nohg_tan",
    "CUP_lmg_Mk48_nohg_od",
    "CUP_lmg_Mk48_nohg_des",
    "CUP_lmg_Mk48_tan",
    "CUP_lmg_Mk48_od",
    "CUP_lmg_Mk48_des",
    "CUP_lmg_Mk48",
    "CUP_srifle_Mk18_wdl",
    "CUP_srifle_Mk18_des",
    "CUP_srifle_Mk18_blk",
    "arifle_Mk20_F",
    "arifle_Mk20_GL_F",
    "arifle_Mk20C_F",
    "srifle_GM6_camo_F",
    "SMG_03C_camo",
    "SMG_03C_hex",
    "SMG_03C_khaki",
    "SMG_03C_TR_camo",
    "SMG_03C_TR_hex",
    "SMG_03C_TR_khaki",
    "SMG_03_camo",
    "SMG_03_hex",
    "SMG_03_khaki",
    "SMG_03_TR_camo",
    "SMG_03_TR_hex",
    "SMG_03_TR_khaki",
    "arifle_MSBS65_camo_F",
    "arifle_MSBS65_sand_F",
    "arifle_MSBS65_GL_camo_F",
    "arifle_MSBS65_GL_sand_F",
    "arifle_MSBS65_Mark_camo_F",
    "arifle_MSBS65_Mark_sand_F",
    "arifle_MSBS65_UBS_camo_F",
    "arifle_MSBS65_UBS_sand_F",
    "arifle_RPK12_arid_F",
    "arifle_RPK12_lush_F",
    "srifle_DMR_05_hex_F",
    "srifle_DMR_05_tan_f",
    "MMG_01_hex_F",
    "srifle_DMR_03_multicam_F",
    "srifle_DMR_03_khaki_F",
    "srifle_DMR_03_tan_F",
    "srifle_DMR_03_woodland_F",
    "CUP_sgun_CZ584",
    "CUP_sgun_CZ584_RIS",
    "CUP_arifle_CZ805_A1_coyote",
    "CUP_arifle_CZ805_GL_coyote",
    "CUP_arifle_CZ805_A2_coyote",
    "HLC_Rifle_XM8_MWSF_Carbine_GL_Green",
    "HLC_Rifle_XM8_MWSF_Carbine_GL_OD",
    "HLC_Rifle_XM8_MWSF_Carbine_GL_Tan",
    "HLC_rifle_XM8_MWSF_Carbine_OD",
    "HLC_rifle_XM8_MWSF_Carbine_Tan",
    "HLC_Rifle_XM8_MWSF_Compact_Green",
    "HLC_Rifle_XM8_MWSF_Compact_OD",
    "HLC_Rifle_XM8_MWSF_Compact_Tan",
    "HLC_Rifle_XM8_MWSF_DMAR_Green",
    "HLC_Rifle_XM8_MWSF_DMAR_OD",
    "HLC_Rifle_XM8_MWSF_DMAR_Tan",
    "hlc_wp_XM177E2_x15",
    "hlc_rifle_m14sopmod_XMAG_grip",
    "hlc_rifle_STG58F_XMAG",
    "hlc_rifle_SAMR_x15",
    "CUP_5x_22_LR_17_HMR_M",
    "CUP_1Rnd_12Gauge_HE",
    "CUP_10x_303_M",
    "CUP_20Rnd_B_AA12_HE",
    "CUP_U_O_RUS_BeigeDigital_MSV",
    "CUP_U_O_RUS_BeigeDigital_MSV_gloves_pads",
    "CUP_U_O_RUS_BeigeDigital_MSV_rolled_up",
    "CUP_U_O_RUS_BeigeDigital_MSV_rolled_up_gloves_pads",
    "CUP_U_O_RUS_EMR_1",
    "CUP_U_O_RUS_EMR_gloves_pads",
    "CUP_U_O_RUS_EMR_2",
    "CUP_U_O_RUS_EMR_rolled_up_gloves_pads",
    "CUP_U_O_RUS_Flora_1",
    "CUP_U_O_RUS_Flora_2",
    "CUP_U_O_RUS_VSR93_MSV",
    "CUP_U_O_RUS_VSR93_MSV_rolled_up",
    "CUP_U_O_RUS_VSR93_worn_MSV",
    "CUP_U_O_RUS_VSR93_worn_gloves_MSV",
    "CUP_U_O_RUS_VSR93_worn_MSV_rolled_up",
    "CUP_U_O_RUS_VSR98_MSV",
    "CUP_U_O_RUS_VSR98_MSV_rolled_up",
    "CUP_U_O_RUS_VSR98_worn_MSV",
    "CUP_U_O_RUS_VSR98_worn_gloves_MSV",
    "CUP_U_O_RUS_VSR98_worn_MSV_rolled_up",
    "CUP_U_O_RUS_BeigeDigital_VDV",
    "CUP_U_O_RUS_BeigeDigital_VDV_gloves_pads",
    "CUP_U_O_RUS_BeigeDigital_VDV_rolled_up",
    "CUP_U_O_RUS_BeigeDigital_VDV_rolled_up_gloves_pads",
    "CUP_U_O_RUS_EMR_1_VDV",
    "CUP_U_O_RUS_EMR_VDV_gloves_pads",
    "CUP_U_O_RUS_EMR_2_VDV",
    "CUP_U_O_RUS_EMR_VDV_rolled_up_gloves_pads",
    "CUP_U_O_RUS_KSOR_VDV",
    "CUP_U_O_RUS_KSOR_VDV_gloves_pads",
    "CUP_U_O_RUS_KSOR_VDV_rolled_up",
    "CUP_U_O_RUS_KSOR_VDV_rolled_up_gloves_pads",
    "CUP_U_O_RUS_Flora_1_VDV",
    "CUP_U_O_RUS_Flora_3",
    "CUP_U_O_RUS_Flora_2_VDV",
    "CUP_U_O_RUS_VSR93_VDV",
    "CUP_U_O_RUS_VSR93_VDV_rolled_up",
    "CUP_U_O_RUS_VSR93_VDV_rolled_up_gloves2",
    "CUP_U_O_RUS_VSR93_worn_VDV",
    "CUP_U_O_RUS_VSR93_worn_gloves_VDV",
    "CUP_U_O_RUS_VSR93_worn_VDV_rolled_up",
    "CUP_U_O_RUS_VSR93_worn_VDV_rolled_up_gloves2",
    "CUP_U_O_RUS_VSR98_VDV",
    "CUP_U_O_RUS_VSR98_VDV_rolled_up",
    "CUP_U_O_RUS_VSR98_VDV_rolled_up_gloves2",
    "CUP_U_O_RUS_VSR98_worn_VDV",
    "CUP_U_O_RUS_VSR98_worn_gloves_VDV",
    "CUP_U_O_RUS_VSR98_worn_VDV_rolled_up",
    "CUP_U_O_RUS_VSR98_worn_VDV_rolled_up_gloves2",
    "CUP_U_O_RUS_Soldier_VKPO_MSV_BeigeDigital_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_MSV_BeigeDigital_rolled_up_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_MSV_EMR_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_MSV_EMR_rolled_up_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_MSV_Pink_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_MSV_Pink_rolled_up_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_VDV_BeigeDigital_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_VDV_BeigeDigital_rolled_up_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_VDV_EMR_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_VDV_EMR_rolled_up_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_VDV_Pink_gloves_pads",
    "CUP_U_O_RUS_Soldier_VKPO_VDV_Pink_rolled_up_gloves_pads",
    "CUP_U_B_CDF_DST_1",
    "CUP_U_B_CDF_DST_2",
    "CUP_U_B_CDF_FST_1",
    "CUP_U_B_CDF_FST_2",
    "CUP_U_B_CDF_MNT_1",
    "CUP_U_B_CDF_MNT_2",
    "CUP_U_B_CDF_SNW_1",
    "CUP_U_B_CDF_SNW_2",
    "CUP_U_O_CHDKZ_Bardak",
    "CUP_U_O_CHDKZ_Lopotev",
    "CUP_U_O_CHDKZ_Kam_03",
    "CUP_U_O_CHDKZ_Kam_01",
    "CUP_U_O_CHDKZ_Kam_02",
    "CUP_U_O_CHDKZ_Commander",
    "CUP_U_O_CHDKZ_Kam_04",
    "CUP_U_O_CHDKZ_Kam_08",
    "CUP_U_O_CHDKZ_Kam_05",
    "CUP_U_O_CHDKZ_Kam_07",
    "CUP_U_C_Citizen_02",
    "CUP_U_C_Citizen_01",
    "CUP_U_C_Citizen_04",
    "CUP_U_C_Citizen_03",
    "CUP_U_CRYE_BLK_RUS_Full",
    "CUP_U_CRYE_BLK_RUS_Roll",
    "CUP_U_CRYE_MCAM_RUS_Full",
    "CUP_U_CRYE_MCAM_RUS_Roll",
    "CUP_U_C_Fireman_01",
    "CUP_U_O_RUS_Gorka_Green",
    "CUP_U_O_RUS_Gorka_Green_gloves2",
    "CUP_U_O_RUS_Gorka_Green_gloves_kneepads",
    "CUP_U_O_RUS_Gorka_Partizan_A",
    "CUP_U_O_RUS_Gorka_Partizan_A_gloves2",
    "CUP_U_O_RUS_Gorka_Partizan_A_gloves_kneepads",
    "CUP_U_O_RUS_Gorka_Partizan",
    "CUP_U_O_RUS_Gorka_Partizan_gloves2",
    "CUP_U_O_RUS_Gorka_Partizan_gloves_kneepads",
    "CUP_O_TKI_Khet_Jeans_04",
    "CUP_O_TKI_Khet_Jeans_02",
    "CUP_O_TKI_Khet_Jeans_01",
    "CUP_O_TKI_Khet_Jeans_03",
    "CUP_O_TKI_Khet_Partug_04",
    "CUP_O_TKI_Khet_Partug_02",
    "CUP_O_TKI_Khet_Partug_01",
    "CUP_O_TKI_Khet_Partug_07",
    "CUP_O_TKI_Khet_Partug_08",
    "CUP_O_TKI_Khet_Partug_05",
    "CUP_O_TKI_Khet_Partug_06",
    "CUP_O_TKI_Khet_Partug_03",
    "CUP_U_C_Labcoat_02",
    "CUP_U_C_Labcoat_03",
    "CUP_U_C_Labcoat_01",
    "CUP_U_O_RUS_Ratnik_BeigeDigital",
    "CUP_U_O_RUS_Ratnik_Pink",
    "CUP_U_O_RUS_Ratnik_Desert",
    "CUP_U_O_RUS_Ratnik_Summer",
    "CUP_U_C_Mechanic_02",
    "CUP_U_C_Mechanic_03",
    "CUP_U_C_Mechanic_01",
    "CUP_U_USNavy_LHD_crew_Blue",
    "CUP_U_USNavy_LHD_crew_Brown",
    "CUP_U_USNavy_LHD_crew_Green",
    "CUP_U_USNavy_LHD_crew_Red",
    "CUP_U_USNavy_LHD_crew_Violet",
    "CUP_U_USNavy_LHD_crew_White",
    "CUP_U_USNavy_LHD_crew_Yellow",
    "CUP_U_O_ODKB_KSOR_VDV",
    "CUP_U_O_ODKB_KSOR_VDV_gloves_pads",
    "CUP_U_O_ODKB_KSOR_VDV_rolled_up",
    "CUP_U_O_ODKB_KSOR_VDV_rolled_up_gloves_pads",
    "CUP_U_O_Partisan_TTsKO",
    "CUP_U_O_Partisan_TTsKO_Mixed",
    "CUP_U_O_Partisan_VSR_Mixed1",
    "CUP_U_O_Partisan_VSR_Mixed2",
    "CUP_U_C_Pilot_01",
    "CUP_U_C_Policeman_01",
    "CUP_U_C_Priest_01",
    "CUP_U_C_Profiteer_02",
    "CUP_U_C_Profiteer_03",
    "CUP_U_C_Profiteer_01",
    "CUP_U_C_Profiteer_04",
    "CUP_U_C_racketeer_01",
    "CUP_U_C_racketeer_04",
    "CUP_U_C_racketeer_02",
    "CUP_U_C_racketeer_03",
    "CUP_U_C_Rocker_01",
    "CUP_U_C_Rocker_03",
    "CUP_U_C_Rocker_02",
    "CUP_U_C_Rocker_04",
    "CUP_U_C_Suit_01",
    "CUP_U_C_Suit_02",
    "CUP_U_C_Suit_03",
    "CUP_U_C_Functionary_jacket_02",
    "CUP_U_C_Functionary_jacket_01",
    "CUP_U_C_Functionary_jacket_03",
    "CUP_U_O_TK_Officer",
    "CUP_U_O_TK_Green",
    "CUP_U_O_TK_MixedCamo",
    "CUP_U_C_Tracksuit_02",
    "CUP_U_C_Tracksuit_01",
    "CUP_U_C_Tracksuit_04",
    "CUP_U_C_Tracksuit_03",
    "CUP_U_O_RUS_M88_MSV",
    "CUP_U_O_RUS_M88_MSV_rolled_up",
    "CUP_U_O_RUS_M88_VDV",
    "CUP_U_O_RUS_M88_VDV_rolled_up",
    "CUP_U_C_Villager_01",
    "CUP_U_C_Villager_04",
    "CUP_U_C_Villager_02",
    "CUP_U_C_Villager_03",
    "CUP_U_C_Woodlander_01",
    "CUP_U_C_Woodlander_02",
    "CUP_U_C_Woodlander_03",
    "CUP_U_C_Woodlander_04",
    "CUP_U_C_Worker_03",
    "CUP_U_C_Worker_04",
    "CUP_U_C_Worker_02",
    "CUP_U_C_Worker_01",
    "CUP_V_RUS_6B45_1_BeigeDigital",
    "CUP_V_RUS_6B45_2_BeigeDigital",
    "CUP_V_RUS_6B45_3_BeigeDigital",
    "CUP_V_RUS_6B45_4_BeigeDigital",
    "CUP_V_RUS_6B45_1",
    "CUP_V_RUS_6B45_2",
    "CUP_V_RUS_6B45_3",
    "CUP_V_RUS_6B45_4",
    "CUP_Vest_RUS_6B45_Sh117_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_PKP_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Del_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Nut_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Del_Nut_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Full_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_Del_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_Nut_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_Del_Nut_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_Full_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_VOG_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Del_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Nut_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Del_Nut_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Full_BeigeDigital",
    "CUP_Vest_RUS_6B45_Sh117_Desert",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Desert",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Del_Desert",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Nut_Desert",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Del_Nut_Desert",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Full_Desert",
    "CUP_Vest_RUS_6B45_Sh117_Del_Desert",
    "CUP_Vest_RUS_6B45_Sh117_Nut_Desert",
    "CUP_Vest_RUS_6B45_Sh117_Del_Nut_Desert",
    "CUP_Vest_RUS_6B45_Sh117_Full_Desert",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Desert",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Del_Desert",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Nut_Desert",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Del_Nut_Desert",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Full_Desert",
    "CUP_Vest_RUS_6B45_Sh117",
    "CUP_Vest_RUS_6B45_Sh117_PKP",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Del",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Nut",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Del_Nut",
    "CUP_Vest_RUS_6B45_Sh117_PKP_Full",
    "CUP_Vest_RUS_6B45_Sh117_Del",
    "CUP_Vest_RUS_6B45_Sh117_Nut",
    "CUP_Vest_RUS_6B45_Sh117_Del_Nut",
    "CUP_Vest_RUS_6B45_Sh117_Full",
    "CUP_Vest_RUS_6B45_Sh117_VOG",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Del",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Nut",
    "CUP_Vest_RUS_6B45_Sh117_VOG_Del_Nut",
    "CUP_Vest_RUS_6B45_Sh117_VOG_full",
    "CUP_V_OI_TKI_Jacket1_04",
    "CUP_V_OI_TKI_Jacket1_06",
    "CUP_V_OI_TKI_Jacket1_01",
    "CUP_V_OI_TKI_Jacket1_05",
    "CUP_V_OI_TKI_Jacket1_02",
    "CUP_V_OI_TKI_Jacket1_03",
    "CUP_V_OI_TKI_Jacket4_04",
    "CUP_V_OI_TKI_Jacket4_05",
    "CUP_V_OI_TKI_Jacket4_02",
    "CUP_V_OI_TKI_Jacket4_06",
    "CUP_V_OI_TKI_Jacket4_03",
    "CUP_V_OI_TKI_Jacket4_01",
    "CUP_V_OI_TKI_Jacket5_04",
    "CUP_V_OI_TKI_Jacket5_05",
    "CUP_V_OI_TKI_Jacket5_02",
    "CUP_V_OI_TKI_Jacket5_06",
    "CUP_V_OI_TKI_Jacket5_03",
    "CUP_V_OI_TKI_Jacket5_01",
    "CUP_V_OI_TKI_Jacket3_04",
    "CUP_V_OI_TKI_Jacket3_02",
    "CUP_V_OI_TKI_Jacket3_03",
    "CUP_V_OI_TKI_Jacket3_05",
    "CUP_V_OI_TKI_Jacket3_06",
    "CUP_V_OI_TKI_Jacket3_01",
    "CUP_V_OI_TKI_Jacket6_04",
    "CUP_V_OI_TKI_Jacket6_05",
    "CUP_V_OI_TKI_Jacket6_02",
    "CUP_V_OI_TKI_Jacket6_06",
    "CUP_V_OI_TKI_Jacket6_03",
    "CUP_V_OI_TKI_Jacket6_01",
    "CUP_V_OI_TKI_Jacket2_04",
    "CUP_V_OI_TKI_Jacket2_06",
    "CUP_V_OI_TKI_Jacket2_03",
    "CUP_V_OI_TKI_Jacket2_02",
    "CUP_V_OI_TKI_Jacket2_05",
    "CUP_V_OI_TKI_Jacket2_01",
    "CUP_H_RUS_6B27_cover_BeigeDigital",
    "CUP_H_RUS_6B27_cover_BeigeDigital_goggles",
    "CUP_H_RUS_6B27_cover_BeigeDigital_headset_goggles",
    "CUP_H_RUS_6B27_cover_BeigeDigital_headset",
    "CUP_H_RUS_6B27_cover",
    "CUP_H_RUS_6B46",
    "CUP_H_RUS_6B27_cover_headset_goggles",
    "CUP_H_RUS_6B27_cover_headset",
    "CUP_H_RUS_6B47_v2_BeigeDigital",
    "CUP_H_RUS_6B47_v2_GogglesClosed_BeigeDigital",
    "CUP_H_RUS_6B47_v2_GogglesDown_BeigeDigital",
    "CUP_H_RUS_6B47_v2_GogglesUp_BeigeDigital",
    "CUP_H_RUS_6B47_v2_Desert",
    "CUP_H_RUS_6B47_v2_GogglesClosed_Desert",
    "CUP_H_RUS_6B47_v2_GogglesDown_Desert",
    "CUP_H_RUS_6B47_v2_GogglesUp_Desert",
    "CUP_H_RUS_6B47_v2_Summer",
    "CUP_H_RUS_6B47_v2_GogglesClosed_Summer",
    "CUP_H_RUS_6B47_v2_GogglesDown_Summer",
    "CUP_H_RUS_6B47_v2_GogglesUp_Summer",
    "CUP_H_RUS_6B47_v2_GogglesClosed_Winter",
    "CUP_H_RUS_6B47_SF_headset_goggles_black",
    "CUP_H_RUS_6B47_SF_headset_black",
    "CUP_H_RUS_6B47_SF_headset_goggles_desert",
    "CUP_H_RUS_6B47_SF_headset_desert",
    "CUP_H_RUS_6B47_SF",
    "CUP_H_RUS_6B47_SF_headset",
    "CUP_H_TK_Lungee",
    "CUP_H_TKI_Lungee_Open_01",
    "CUP_H_TKI_Lungee_Open_02",
    "CUP_H_TKI_Lungee_Open_03",
    "CUP_H_TKI_Lungee_Open_04",
    "CUP_H_TKI_Lungee_Open_05",
    "CUP_H_TKI_Lungee_Open_06",
    "CUP_H_TKI_Lungee_01",
    "CUP_H_TKI_Lungee_02",
    "CUP_H_TKI_Lungee_03",
    "CUP_H_TKI_Lungee_04",
    "CUP_H_TKI_Lungee_05",
    "CUP_H_TKI_Lungee_06",
    "CUP_H_TKI_Pakol_1_01",
    "CUP_H_TKI_Pakol_2_04",
    "CUP_H_TKI_Pakol_2_05",
    "CUP_H_TKI_Pakol_2_06",
    "CUP_H_TKI_Pakol_1_02",
    "CUP_H_TKI_Pakol_1_03",
    "CUP_H_TKI_Pakol_1_04",
    "CUP_H_TKI_Pakol_1_05",
    "CUP_H_TKI_Pakol_1_06",
    "CUP_H_TKI_Pakol_2_01	",
    "CUP_H_TKI_Pakol_2_02",
    "CUP_H_TKI_Pakol_2_03",
    "CUP_H_TKI_SkullCap_01",
    "CUP_H_TKI_SkullCap_02",
    "CUP_H_TKI_SkullCap_03",
    "CUP_H_TKI_SkullCap_04",
    "CUP_H_TKI_SkullCap_05",
    "CUP_H_TKI_SkullCap_06",
    "hlc_rifle_G36MLIC",
    "hlc_rifle_G36MLIAG36",
    "hlc_rifle_G36CMLIC",
    "hlc_rifle_G36E1AG36_Romi",
    "hlc_rifle_G36KMLIC",
    "hlc_rifle_416D10_RAHG",
    "ffaa_armas_hkg36e_tir",
    "ffaa_armas_hkg36k_normal",
    "ffaa_armas_hkg36k",
    "ffaa_armas_hkg36k_tir",
    "hlc_rifle_saiga12k",
    "hlc_rifle_416N",
    "hlc_rifle_hk53",
    "hlc_rifle_hk53RAS",
    "hlc_smg_mp5A2_Sfire",
    "hlc_rifle_M1941LMG",
    "hlc_rifle_SLR",
    "hlc_rifle_SLRchopmod",
    "hlc_rifle_M14_Bipod",
    "hlc_rifle_M1903A1",
    "hlc_rifle_M1903A1OMR",
    "hlc_rifle_M1903A1_unertl",
    "hlc_rifle_ACR_SBR_cliffhanger",
    "hlc_rifle_ACR_carb_green",
    "hlc_rifle_ACR_SBR_green",
    "hlc_rifle_ACR_GL_SBR_cliffhanger",
    "hlc_rifle_ACR_GL_Carb_green",
    "hlc_rifle_ACR_GL_SBR_green",
    "hlc_rifle_ACR_GL_mid_green",
    "hlc_rifle_ACR_Full_green",
    "hlc_rifle_ACR_MID_green",
    "hlc_rifle_ACR68_carb_green",
    "hlc_rifle_ACR68_SBR_green",
    "hlc_rifle_ACR68_GL_Carb_green",
    "hlc_rifle_ACR68_GL_SBR_green",
    "hlc_rifle_ACR68_GL_mid_green",
    "hlc_rifle_ACR68_full_green",
    "hlc_rifle_ACR68_MID_green",
    "hlc_rifle_STGW57",
    "hlc_rifle_stgw57_RIS",
    "hlc_rifle_stgw57_commando",
    "hlc_rifle_STGW57_RG",
    "hlc_rifle_stgw57_RIS_RG",
    "hlc_rifle_augsr",
    "hlc_rifle_augsr_t",
    "hlc_rifle_augsrcarb",
    "hlc_rifle_augsrcarb_t",
    "hlc_rifle_augsrhbar",
    "hlc_rifle_augsrhbar_t",
    "hlc_rifle_aug",
    "hlc_rifle_auga1_t",
    "hlc_rifle_auga1carb",
    "hlc_rifle_auga1carb_t",
    "hlc_rifle_aughbar",
    "hlc_rifle_aughbar_t",
    "hlc_rifle_augpara",
    "hlc_rifle_augpara_t",
    "hlc_rifle_auga2",
    "hlc_rifle_auga2_t",
    "hlc_rifle_auga2carb",
    "hlc_rifle_auga2carb_t",
    "hlc_rifle_auga2lsw",
    "hlc_rifle_auga2lsw_t",
    "hlc_rifle_auga2para",
    "hlc_rifle_auga2para_t",
    "hlc_rifle_auga2para_t",
    "hlc_rifle_auga3_GL_BL",
    "HLC_rifle_XM8_Carbine",
    "HLC_rifle_XM8_Carbine_GL",
    "HLC_rifle_XM8_Carbine_GL_green",
    "HLC_rifle_XM8_Carbine_GL_OD",
    "HLC_rifle_XM8_Carbine_GL_Tan",
    "HLC_Rifle_XM8_Proto_Carbine",
    "HLC_rifle_XM8_Proto_Carbine_GL",
    "HLC_rifle_XM8_Proto_Carbine_GL_Green",
    "HLC_rifle_XM8_Proto_Carbine_GL_OD",
    "HLC_rifle_XM8_Proto_Carbine_GL_Tan",
    "HLC_rifle_XM8_Proto_Carbine_Green",
    "HLC_rifle_XM8_Proto_Carbine_OD",
    "HLC_rifle_XM8_Proto_Carbine_Tan",
    "HLC_rifle_XM8_Carbine_Fish",
    "HLC_rifle_XM8_Carbine_Green",
    "HLC_rifle_XM8_Carbine_OD",
    "HLC_rifle_XM8_Carbine_Tan",
    "hlc_rifle_XM8_Compact",
    "hlc_rifle_XM8_Proto_Compact",
    "HLC_rifle_XM8_Proto_Compact_Green",
    "HLC_rifle_XM8_Proto_Compact_OD",
    "HLC_rifle_XM8_Proto_Compact_Tan",
    "HLC_rifle_XM8_Compact_Green",
    "HLC_rifle_XM8_Compact_OD",
    "HLC_rifle_XM8_Compact_Tan",
    "hlc_rifle_XM8_DMAR",
    "hlc_rifle_XM8_Proto_DMAR",
    "HLC_rifle_XM8_Proto_DMAR_Green",
    "HLC_rifle_XM8_Proto_DMAR_OD",
    "HLC_rifle_XM8_DMAR_Green",
    "HLC_rifle_XM8_DMAR_OD",
    "HLC_rifle_XM8_DMAR_Custom",
    "HLC_rifle_XM8_DMAR_Tan",
    "hlc_isopod",
    "hlc_rifle_SG551LB_RIS",
    "hlc_panel_under_ladder_l_black",
    "hlc_panel_under_ladder_l_desert",
    "hlc_panel_under_ladder_l_rg",
    "hlc_panel_under_ladder_l_od",
    "hlc_panel_under_ladder_l_pride",
    "hlc_panel_under_ladder_m_black",
    "hlc_panel_under_ladder_m_desert",
    "hlc_panel_under_ladder_m_rg",
    "hlc_panel_under_ladder_m_od",
    "hlc_panel_under_ladder_m_pride",
    "hlc_panel_under_ladder_s_black",
    "hlc_panel_under_ladder_s_desert",
    "hlc_panel_under_ladder_s_rg",
    "hlc_panel_under_ladder_s_od",
    "hlc_panel_under_ladder_s_pride",
    "hlc_panel_under_magpulxt_black",
    "hlc_panel_under_magpulxt_desert",
    "hlc_panel_under_magpulxt_rg",
    "hlc_panel_under_magpulxt_od",
    "hlc_panel_under_magpulxt_pride",
    "hlc_panel_under_2xxtme_black",
    "hlc_panel_under_2xxtme_desert",
    "hlc_panel_under_2xxtme_rg",
    "hlc_panel_under_2xxtme_od",
    "hlc_panel_under_4xxtme_black",
    "hlc_panel_under_4xxtme_desert",
    "hlc_panel_under_4xxtme_rg",
    "hlc_panel_under_4xxtme_od",
    "hlc_panel_under_6xxtme_black",
    "hlc_panel_under_6xxtme_desert",
    "hlc_panel_under_6xxtme_rg",
    "hlc_panel_under_6xxtme_od",
    "hlc_panel_under_xtme_black",
    "hlc_panel_under_xtme_desert",
    "hlc_panel_under_xtme_rg",
    "hlc_panel_under_xtme_od",
    "hlc_panel_under_fn10cm_black",
    "hlc_panel_under_fn10cm_desert",
    "hlc_panel_under_fn10cm_rg",
    "hlc_panel_under_fn10cm_od",
    "hlc_panel_under_fn15cm_black",
    "hlc_panel_under_fn15cm_desert",
    "hlc_panel_under_fn15cm_rg",
    "hlc_panel_under_fn15cm_od",
    "hlc_panel_under_2xfn5cm_black",
    "hlc_panel_under_2xfn5cm_desert",
    "hlc_panel_under_2xfn5cm_rg",
    "hlc_panel_under_2xfn5cm_od",
    "hlc_panel_under_fn5cm_black",
    "hlc_panel_under_fn5cm_desert",
    "hlc_panel_under_fn5cm_rg",
    "hlc_panel_under_ladder_s_rg",
    "hlc_panel_under_ladder_s_od",
    "hlc_panel_under_ladder_s_pride",
    "hlc_panel_under_magpulxt_black",
    "hlc_panel_under_magpulxt_desert",
    "hlc_panel_under_magpulxt_rg",
    "hlc_panel_under_magpulxt_od",
    "hlc_panel_under_magpulxt_pride",
    "hlc_panel_under_2xxtme_black",
    "hlc_panel_under_2xxtme_desert",
    "hlc_panel_under_2xxtme_rg",
    "hlc_panel_under_2xxtme_od",
    "hlc_panel_under_4xxtme_black",
    "hlc_panel_under_4xxtme_desert",
    "hlc_panel_under_4xxtme_rg",
    "hlc_panel_under_4xxtme_od",
    "hlc_panel_under_6xxtme_black",
    "hlc_panel_under_6xxtme_desert",
    "hlc_panel_under_6xxtme_rg",
    "hlc_panel_under_6xxtme_od",
    "hlc_panel_under_xtme_black",
    "hlc_panel_under_xtme_desert",
    "hlc_panel_under_xtme_rg",
    "hlc_panel_under_xtme_od",
    "hlc_panel_under_fn10cm_black",
    "hlc_panel_under_fn10cm_desert",
    "hlc_panel_under_fn10cm_rg",
    "hlc_rifle_ak74_dirty",
    "hlc_rifle_ak74m",
    "hlc_rifle_akm_MTK",
    "hlc_panel_under_6xxtme_od",
    "hlc_panel_under_xtme_black",
    "hlc_panel_under_xtme_desert",
    "hlc_panel_under_xtme_rg",
    "hlc_panel_under_xtme_od",
    "hlc_panel_under_fn10cm_black",
    "hlc_panel_under_fn10cm_desert",
    "hlc_panel_under_fn10cm_rg",
    "hlc_panel_under_6xxtme_black",
    "hlc_panel_under_6xxtme_desert",
    "hlc_panel_under_6xxtme_rg",
    "hlc_panel_under_6xxtme_od",
    "hlc_panel_under_xtme_black",
    "hlc_panel_under_xtme_desert",
    "hlc_panel_under_xtme_rg",
    "hlc_panel_under_xtme_od",
    "hlc_panel_under_fn10cm_black",
    "hlc_panel_under_fn10cm_desert",
    "hlc_panel_under_fn10cm_rg",
    "CUP_srifle_CZ550_base",
    "CUP_srifle_CZ550",
    "CUP_srifle_CZ550_rail",
    "CUP_srifle_LeeEnfield",
    "CUP_srifle_LeeEnfield_rail",
    "CUP_srifle_M14_DMR",
    "CUP_srifle_M14_DMR_LeupoldMk4",
    "CUP_srifle_M14_DMR_LeupoldMk4_snds",
    "CUP_srifle_DMR",
    "CUP_srifle_DMR_LeupoldMk4",
    "CUP_srifle_DMR_LeupoldMk4_snds",
    "CUP_arifle_OTS14_GROZA_Base",
    "CUP_arifle_OTS14_GROZA_GL",
    "CUP_arifle_OTS14_GROZA_Grip",
    "CUP_arifle_OTS14_GROZA",
    "CUP_arifle_AUG_A1",
    "CUP_lmg_UK59",
    "CUP_srifle_VSSVintorez",
    "CUP_srifle_VSSVintorez_top_rail",
    "CUP_srifle_VSSVintorez_VFG",
    "CUP_srifle_VSSVintorez_VFG_top_rail",
    "CUP_srifle_VSSVintorez_flash",
    "CUP_srifle_VSSVintorez_flash_top",
    "CUP_arifle_AS_VAL",
    "CUP_arifle_AS_VAL_top_rail",
    "CUP_arifle_AS_VAL_VFG",
    "CUP_arifle_AS_VAL_VFG_top_rail",
    "CUP_arifle_AS_VAL_flash",
    "CUP_arifle_AS_VAL_flash_top",
    "CUP_arifle_SR3M_Vikhr",
    "CUP_arifle_SR3M_Vikhr_top_rail",
    "CUP_arifle_SR3M_Vikhr_VFG",
    "CUP_arifle_SR3M_Vikhr_VFG_top_rail",
    "CUP_srifle_VSSVintorez_pso",
    "CUP_arifle_AS_VAL_pso",
    "CUP_arifle_SR3M_Vikhr_VFG_snds",
    "CUP_arifle_SAIGA_MK03",
    "CUP_arifle_SAIGA_MK03_top_rail",
    "CUP_arifle_SAIGA_MK03_Wood",
    "CUP_arifle_SIAGE_MK03_Wood_top_rail",
    "CUP_smg_vityaz",
    "CUP_smg_vityaz_vfg",
    "CUP_smg_vityaz_top_rail",
    "CUP_smg_vityaz_vfg_top_rail",
    "CUP_smg_vityaz_vfg_front_rail",
    "CUP_smg_saiga9",
    "CUP_arifle_FNFAL",
    "CUP_arifle_FNFAL5061",
    "CUP_arifle_FNFAL5062",
    "CUP_arifle_FNFAL_OSW",
    "CUP_arifle_FNFAL_railed",
    "CUP_arifle_FNFAL_ANPVS4",
    "CUP_arifle_G36A",
    "CUP_arifle_G36A_camo",
    "CUP_arifle_G36A_wdl",
    "CUP_arifle_G36A_RIS",
    "CUP_arifle_G36A_RIS_camo",
    "CUP_arifle_G36A_RIS_wdl",
    "CUP_arifle_AG36",
    "CUP_arifle_AG36_camo",
    "CUP_arifle_AG36_wdl",
    "CUP_arifle_G36A_AG36_RIS",
    "CUP_arifle_G36A_AG36_RIS_camo",
    "CUP_arifle_G36A_AG36_RIS_wdl",
    "CUP_arifle_G36K",
    "CUP_arifle_G36K_camo",
    "CUP_arifle_G36K_wdl",
    "CUP_arifle_G36K_VFG",
    "CUP_arifle_G36K_VFG_camo",
    "CUP_arifle_G36K_VFG_wdl",
    "CUP_arifle_G36K_RIS",
    "CUP_arifle_G36K_RIS_camo",
    "CUP_arifle_G36K_RIS_wdl",
    "CUP_arifle_G36K_RIS_hex",
    "CUP_arifle_G36K_AG36",
    "CUP_arifle_G36K_AG36_camo",
    "CUP_arifle_G36K_AG36_wdl",
    "CUP_arifle_G36K_RIS_AG36",
    "CUP_arifle_G36K_RIS_AG36_camo",
    "CUP_arifle_G36K_RIS_AG36_wdl",
    "CUP_arifle_G36K_RIS_AG36_hex",
    "CUP_arifle_G36C",
    "CUP_arifle_G36C_camo",
    "CUP_arifle_G36C_wdl",
    "CUP_arifle_G36C_hex",
    "CUP_arifle_G36C_VFG",
    "CUP_arifle_G36C_VFG_camo",
    "CUP_arifle_G36C_VFG_wdl",
    "CUP_arifle_G36C_VFG_hex",
    "CUP_arifle_G36C_VFG_Carry",
    "CUP_arifle_MG36",
    "CUP_arifle_MG36_camo",
    "CUP_arifle_MG36_wdl",
    "CUP_arifle_MG36_hex",
    "CUP_arifle_G36C_holo_snds",
    "CUP_arifle_G36C_camo_holo_snds",
    "CUP_arifle_MG36_holo",
    "CUP_arifle_MG36_camo_holo",
    "CUP_arifle_HK416_CQB_Black",
    "CUP_arifle_HK416_CQB_Desert",
    "CUP_arifle_HK416_CQB_Wood",
    "CUP_arifle_HK416_Black",
    "CUP_arifle_HK416_Desert",
    "CUP_arifle_HK416_Wood",
    "CUP_arifle_HK_M27",
    "CUP_arifle_HK_M27_VFG",
    "CUP_arifle_HK416_M203_Black",
    "CUP_arifle_HK416_M203_Desert",
    "CUP_arifle_HK416_M203_Wood",
    "CUP_arifle_HK416_CQB_M203_Black",
    "CUP_arifle_HK416_CQB_M203_Desert",
    "CUP_arifle_HK416_CQB_M203_Wood",
    "CUP_arifle_HK416_AGL_Black",
    "CUP_arifle_HK416_AGL_Desert",
    "CUP_arifle_HK416_AGL_Wood",
    "CUP_arifle_HK416_CQB_AG36",
    "CUP_arifle_HK416_CQB_AG36_Desert",
    "CUP_arifle_HK416_CQB_AG36_Wood",
    "CUP_arifle_HK_M27_AG36",
    "CUP_arifle_M27_ACOG",
    "CUP_arifle_M16A2",
    "CUP_arifle_M16A2_GL",
    "CUP_arifle_M16A4_Base",
    "CUP_arifle_M16A4_Grip",
    "CUP_arifle_M16A4_GL",
    "CUP_arifle_XM16E1",
    "CUP_arifle_M16A1",
    "CUP_arifle_M16A1GL",
    "CUP_arifle_M16A1GL_USA",
    "CUP_arifle_M16A1GL_FS",
    "CUP_arifle_M4A1",
    "CUP_arifle_M4A1_desert_carryhandle",
    "CUP_arifle_M4A1_camo_carryhandle",
    "CUP_arifle_M4A1_GL_carryhandle",
    "CUP_arifle_M4A1_GL_carryhandle_camo",
    "CUP_arifle_M4A1_GL_carryhandle_desert",
    "CUP_arifle_M4A1_camo",
    "CUP_arifle_M4A1_black",
    "CUP_arifle_M4A1_desert",
    "CUP_arifle_M4A1_BUIS_GL",
    "CUP_arifle_M4A1_BUIS_camo_GL",
    "CUP_arifle_M4A1_BUIS_desert_GL",
    "CUP_arifle_M4A3_desert",
    "CUP_arifle_M4A3_camo",
    "CUP_arifle_M4A3_black",
    "CUP_arifle_SBR_black",
    "CUP_arifle_SBR_od",
    "CUP_arifle_M16A4_Aim_Laser",
    "CUP_arifle_M16A4_ACOG_Laser",
    "CUP_arifle_M16A4_GL_Laser",
    "CUP_arifle_M16A4_GL_ACOG_Laser",
    "CUP_arifle_M4A1_camo_Aim",
    "CUP_arifle_M4A3_desert_Aim_Flashlight",
    "CUP_arifle_M4A3_desert_GL_ACOG_Laser",
    "CUP_arifle_M4A1_Aim",
    "CUP_arifle_M4A1_camo_AIM_snds",
    "CUP_arifle_M4A1_GL_Holo_Flashlight",
    "CUP_arifle_M4A1_GL_ACOG_Flashlight",
    "CUP_arifle_M4A1_camo_GL_Holo_Flashlight",
    "CUP_arifle_M4A1_camo_GL_Holo_Flashlight_Snds",
    "CUP_srifle_Mk12SPR_LeupoldM3LR",
    "CUP_srifle_Mk12SPR_LeupoldM3LR_bipod",
    "CUP_arifle_M4A1_LeupoldMk4MRT",
    "CUP_arifle_M4A1_Aim_Laser_snds",
    "CUP_arifle_M4A1_M203_Holo_Laser",
    "CUP_arifle_M4A1_Holo",
    "CUP_arifle_M4A1_M203_ACOG_Laser",
    "CUP_arifle_M4A1_M203_ANPAS13c1_Laser",
    "CUP_arifle_M4A1_Holo_Laser",
    "CUP_arifle_M4A1_LeupoldMk4CQT_Laser",
    "CUP_arifle_M4A1_ACOG_Laser",
    "CUP_arifle_M4A1_ACOG_flashlight",
    "CUP_arifle_M4A1_CCO_Laser",
    "CUP_arifle_M4A1_CCO_flashlight",
    "CUP_lmg_minimipara",
    "CUP_lmg_minimi",
    "CUP_lmg_m249_para",
    "CUP_lmg_m249_para_gl",
    "CUP_lmg_M249_E2",
    "CUP_lmg_minimi_railed",
    "CUP_lmg_m249_pip1",
    "CUP_lmg_M249",
    "CUP_lmg_m249_pip2",
    "CUP_lmg_m249_pip3",
    "CUP_lmg_m249_pip4",
    "CUP_lmg_m249_SQuantoon",
    "CUP_lmg_M249_ElcanM145_Laser",
    "CUP_lmg_M249_Laser",
    "CUP_lmg_M249_ANPAS13c2_Laser",
    "CUP_lmg_MG3",
    "CUP_lmg_MG3_rail",
    "CUP_lmg_MG3_M145",
    "hlc_pistol_C96_Wartime",
    "hlc_pistol_C96_Custom",
    "hlc_pistol_C96_Wartime_stock",
    "hlc_pistol_C96_Wartime_Worn",
    "hlc_pistol_C96_Wartime_Worn_stock",
    "hlc_pistol_C96_Prussian",
    "hlc_pistol_C96_Prussian_Rework",
    "hlc_pistol_C96_Prussian_stock",
    "hlc_pistol_C96_Prussian_Rework_stock",
    "hlc_pistol_C96_Bolo",
    "hlc_pistol_C96_Bolo_stock",
    "hlc_pistol_C96_Bolo_Worn",
    "hlc_pistol_C96_Bolo_Worn_stock",
    "hlc_pistol_M712",
    "hlc_pistol_M712_stock",
    "hlc_pistol_M712_Worn",
    "hlc_pistol_M712_worn_stock",
    "HLC_wp_M134Painless",
    "hlc_pistol_DL44",
    "hlc_rifle_bab",
    "Titan_AT",
    "Titan_AP",
    "Titan_AA",
    "B_UavTerminal",
    "O_UavTerminal",
    "I_UavTerminal",
    "C_UavTerminal",
    "I_UAV_06_backpack_F",
    "O_UAV_06_backpack_F",
    "B_UAV_06_backpack_F",
    "I_UAV_06_medical_backpack_F",
    "O_UAV_06_medical_backpack_F",
    "C_IDAP_UAV_06_medical_backpack_F",
    "B_UAV_06_medical_backpack_F",
    "I_UAV_01_backpack_F",
    "O_UAV_01_backpack_F",
    "B_UAV_01_backpack_F",
    "C_IDAP_UAV_06_antimine_backpack_F",
    "C_UAV_06_backpack_F",
    "C_IDAP_UAV_06_backpack_F",
    "C_UAV_06_medical_backpack_F",
    "C_IDAP_UAV_01_backpack_F",
    "I_E_UAV_06_backpack_F",
    "I_E_UAV_06_medical_backpack_F",
    "I_E_UAV_01_backpack_F",
    "launch_I_Titan_eaf_F",
    "launch_B_Titan_olive_F",
    "launch_B_Titan_tna_F",
    "launch_B_Titan_short_tna_F",
    "launch_O_Titan_ghex_F",
    "launch_O_Titan_short_ghex_F",
    "launch_B_Titan_F",
    "launch_I_Titan_F",
    "launch_O_Titan_F",
    "launch_Titan_F",
    "launch_B_Titan_short_F",
    "launch_I_Titan_short_F",
    "launch_O_Titan_short_F",
    "launch_Titan_short_F",
    "B_Static_Designator_01_weapon_F",
    "B_W_Static_Designator_01_weapon_F",
    "O_Static_Designator_02_weapon_F",
    "B_UGV_02_Science_backpack_F",
    "O_UGV_02_Science_backpack_F",
    "I_UGV_02_Science_backpack_F",
    "B_UGV_02_Demining_backpack_F",
    "O_UGV_02_Demining_backpack_F",
    "I_UGV_02_Demining_backpack_F",
    "land_Tentdome_F",
    "B_Respawn_sleeping_bag_blue_F",
    "B_Respawn_sleeping_bag_brown_F",
    "B_Respawn_Tentdome_F",
    "B_Respawn_sleeping_bag_F",
    "B_Respawn_TentA_F",
    "B_Patrol_Respawn_bag_F",
    "B_Patrol_Respawn_tent_F",
    "B_HMG_01_support_F",
    "O_HMG_01_support_F",
    "I_HMG_01_support_F",
    "B_HMG_01_support_high_F",
    "O_HMG_01_support_high_F",
    "I_HMG_01_support_high_F",
    "I_HMG_01_A_weapon_F",
    "B_HMG_01_A_weapon_F",
    "O_HMG_01_A_weapon_F",
    "O_HMG_01_weapon_F",
    "B_HMG_01_weapon_F",
    "I_HMG_01_weapon_F",
    "I_HMG_01_high_weapon_F",
    "O_HMG_01_high_weapon_F",
    "B_HMG_01_high_weapon_F",
    "B_HMG_01_support_grn_F",
    "B_HMG_01_Weapon_grn_F",
    "B_HMG_02_high_weapon_F",
    "B_G_HMG_02_high_weapon_F",
    "I_HMG_02_high_weapon_F",
    "O_HMG_02_high_weapon_F",
    "B_HMG_02_support_F",
    "B_G_HMG_02_support_F",
    "I_HMG_02_support_F",
    "O_HMG_02_support_F",
    "B_HMG_02_support_high_F",
    "B_G_HMG_02_support_high_F",
    "I_HMG_02_support_high_F",
    "O_HMG_02_support_high_F",
    "B_HMG_02_weapon_F",
    "B_G_HMG_02_weapon_F",
    "I_HMG_02_weapon_F",
    "O_HMG_02_weapon_F",
    "I_GMG_01_A_weapon_F",
    "O_GMG_01_A_weapon_F",
    "B_GMG_01_A_weapon_F",
    "O_GMG_01_weapon_F",
    "I_GMG_01_weapon_F",
    "B_GMG_01_weapon_F",
    "B_GMG_01_high_weapon_F",
    "I_GMG_01_high_weapon_F",
    "O_GMG_01_high_weapon_F",
    "I_Mortar_01_support_F",
    "B_Mortar_01_support_F",
    "O_Mortar_01_support_F",
    "B_Mortar_01_weapon_F",
    "O_Mortar_01_weapon_F",
    "I_Mortar_01_weapon_F",
    "B_AA_01_weapon_F",
    "O_AA_01_weapon_F",
    "I_AA_01_weapon_F",
    "B_AT_01_weapon_F",
    "O_AT_01_weapon_F",
    "I_AT_01_weapon_F",
    "I_UAV_01_backpack_F",
    "B_UAV_01_backpack_F",
    "O_UAV_01_backpack_F",
    "B_Mortar_01_support_grn_F",
    "B_GMG_01_Weapon_grn_F",
    "B_Mortar_01_Weapon_grn_F",
    "B_Protagonist_VR_F",
    "U_B_Protagonist_VR",
    "O_Protagonist_VR_F",
    "U_O_Protagonist_VR",
    "I_Protagonist_VR_F",
    "U_I_Protagonist_VR",
    "C_Protagonist_VR_F",
    "TFAR_rf7800str",
    "C_UavTerminal",
    "I_E_UavTerminal",
    "O_UavTerminal",
    "TFAR_pnr1000a",
    "TFAR_pnr1000a",
    "TFAR_fadak",
    "I_UavTerminal",
    "TFAR_anprc154",
    "TFAR_anprc148jem",
    "U_C_Protagonist_VR",
    "optic_Nightstalker",
    "optic_tws",
    "optic_tws_mg",
    "optic_NVS",
    "NVgoggles_tna_F",
    "NVgogglesB_blk_F",
    "NVgogglesB_grn_F",
    "NVgogglesB_gry_F",
    "H_Helmeto_ViperSP_hex_F",
    "H_Helmeto_ViperSP_ghex_F",
    "U_O_V_Soldier_Viper_hex_F",
    "U_O_V_Soldier_Viper_F",
    "O_V_Soldier_Viper_F",
    "CUP_U_C_Priest_01",
    "CUP_launch_Javelin",
    "CUP_Javelin_M",
    "arifle_ARX_blk_F",
    "arifle_ARX_hex_F",
    "arifle_ARX_ghex_F",
    "CUP_arifle_type_56_2_Early",
    "CUP_arifle_type_56_2",
    "CUP_arifle_type_56_2_top_rail",
    "CUP_lmg_UK59",
    "CUP_sgun_slamfire",
    "O_V_Soldier_Viper_hex_F",
    "ffaa_spike_tripode_Bag",
    "Redd_Tank_M120_Tampella_Tripod",
    "Redd_Tank_M120_Tampella_Barrel",
    "rnt_mg3_static_barell_ai",
    "rnt_mg3_static_tripod_ai",
    "H_HelmetO_ViperSP_ghex_F",
    "H_HelmetO_ViperSP_hex_F",
	"NVGogglesB_blk_F",
	"NVGogglesB_grn_F",
	"NVGogglesB_gry_F",
	"CUP_hgun_Browning_HP",
	"KKiv_Mag_HEDP",
    "CUP_arifle_AK19_AFG_snowtiger",
    "CUP_arifle_AK19_AFG_tiger",
    "CUP_arifle_AK19_VG_snowtiger",
    "CUP_arifle_AK19_VG_tiger",
    "CUP_arifle_AK19_GP34_snowtiger",
    "CUP_arifle_AK19_GP34_tiger",
    "CUP_arifle_AK19_snowtiger",
    "CUP_arifle_AK19_tiger",
    "CUP_arifle_AK12_AFG_snowtiger",
    "CUP_arifle_AK12_AFG_tiger",
    "CUP_arifle_AK12_VG_snowtiger",
    "CUP_arifle_AK12_VG_tiger",
    "CUP_arifle_AK12_GP34_snowtiger",
    "CUP_arifle_AK12_GP34_tiger",
    "CUP_arifle_AK12_snowtiger",
    "CUP_arifle_AK12_tiger",
    "CUP_arifle_AK15_AFG_snowtiger",
    "CUP_arifle_AK15_AFG_tiger",
    "CUP_arifle_AK15_VG_snowtiger",
    "CUP_arifle_AK15_VG_tiger",
    "CUP_arifle_AK15_GP34_snowtiger",
    "CUP_arifle_AK15_GP34_tiger",
    "CUP_arifle_AK15_snowtiger",
    "CUP_arifle_AK15_tiger"
];

